# engine/keywords_openformat.py
"""Open-format genre keyword lists. Pure data — no logic.

Adds 11 new genre buckets to the existing 13-genre taxonomy in keywords.py,
built for wedding and party DJs running an open-format set (techno through
2000s throwbacks). Style matches keywords.py: plain lowercase strings, grouped
under short comments, artists weighted heavier than genre terms.

Quality notes:
  - Short ambiguous words are padded with spaces or dropped to avoid false
    positives (e.g. "punk" alone would over-match "post-punk"/"punk rock").
  - Artists are not repeated across two lists unless they genuinely span both.
  - This module is independent of GENRE_KEYWORDS in keywords.py; wire
    OPENFORMAT_KEYWORDS into the classifier separately when ready.
"""

TECHNO_KEYWORDS = [
    # ─ Techno artists ─
    "charlotte de witte",
    "amelie lens",
    "adam beyer",
    "carl cox",
    "richie hawtin",
    "boris brejcha",
    "chris liebing",
    "nina kraviz",
    "joseph capriati",
    "ben klock",
    "marcel dettmann",
    "len faki",
    "speedy j",
    "surgeon ",
    "blawan ",
    "dax j ",
    "sven vath", "sven väth",
    "paul kalkbrenner",
    "pan-pot", "pan pot",
    "reinier zonneveld",
    "adiel ",
    "adam beyer presents",
    # ─ Tech house artists ─
    "fisher ", "fisher_",
    "chris lake",
    "solardo",
    "patrick topping",
    "hot since 82",
    "green velvet",
    "jamie jones",
    "michael bibi",
    "camelphat",
    "cloonee",
    "mau p", "mau_p",
    "james hype",
    "biscits",
    "dennis cruz",
    "cristoph",
    "eli brown",
    "acraze",
    "james hurr",
    "west end",
    "cheney thomas",
    "layton giordani",
    "vintage culture",
    "gorgon city",
    "sonny fodera",
    "cassian ",
    "fred again",
    "disclosure",
    # ─ Labels ─
    "drumcode",
    "ninja tune",
    "hot creations",
    "solid grooves",
    "afterlife records",
    "diynamic",
    "kompakt records",
    "cocoon recordings",
    "tronic records",
    "second state",
    "repopulate mars",
    "knee deep in sound",
    "realm records",
    # ─ Genre terms ─
    "techno ", "tech house",
    "minimal techno",
    "peak time techno", "peak-time techno",
    "industrial techno",
    "melodic techno",
    "warehouse rave", "warehouse set",
    "hypnotic techno",
    "raw techno",
    "hard techno",
    "detroit techno",
    "berlin techno",
    "acid techno",
    "afro tech",
    "groove techno",
]

TRANCE_KEYWORDS = [
    # ─ Trance artists ─
    "armin van buuren",
    "above & beyond", "above and beyond",
    "paul van dyk",
    "ferry corsten",
    "gareth emery",
    "andrew rayel",
    "markus schulz",
    "john o'callaghan",
    "aly & fila", "aly and fila",
    "cosmic gate",
    "dash berlin",
    "giuseppe ottaviani",
    "orjan nilsen", "ørjan nilsen",
    "ilan bluestone",
    "will atkinson",
    "solarstone",
    "bryan kearney",
    "mark sixma",
    "sunny lax",
    "ferry tayle",
    "genix ",
    "andrew bayer",
    "signum ",
    "super8 & tab", "super8 and tab",
    # ─ Psytrance artists ─
    "vini vici",
    "astrix ",
    "infected mushroom",
    "ace ventura",
    "captain hook",
    "berg ",
    "skazi ",
    "talamasca",
    "x-dream", "x dream",
    "juno reactor",
    "hallucinogen",
    "shpongle",
    "1200 micrograms", "1200 mics",
    "sonic species",
    "vertical mode",
    "outsiders",
    "khainz",
    "atmos ",
    "liquid soul",
    "sesto sento",
    "space tribe",
    "electric universe",
    # ─ Genre / event terms ─
    "trance ", "psytrance", "psy trance", "psy-trance",
    "goa trance", "progressive trance",
    "uplifting trance",
    "vocal trance",
    "hard trance",
    "asot ", "a state of trance",
    "anjunabeats",
    "anjunadeep",
    "hi-tech psy", "hi tech psy",
    "full on", "fullon",
    "dark psy", "dark psytrance",
    "suomisaundi",
    "tech trance",
    "trance classics",
    "trance anthem",
    "trance festival",
    "trance vocal remix",
    "psybient",
    "psychill",
    "ambient psy",
    "trance pioneer",
    "trance set",
]

DUBSTEP_KEYWORDS = [
    # ─ Dubstep / bass artists ─
    "skrillex",
    "excision",
    "subtronics",
    "virtual riot",
    "svdden death",
    "zomboy",
    "ganja white night",
    "boogie t",
    "rusko ",
    "flux pavilion",
    "doctor p",
    "hamdi ",
    "barely alive",
    "must die",
    "must die!",
    "getter ",
    "cookie monsta",
    "borgore",
    "12th planet",
    "datsik",
    "caspa ",
    "rise at night",
    "dion timmer",
    "wooli ",
    "space laces",
    "kompany",
    "of the trees",
    "eptic ",
    "seven lions",
    "champagne drip",
    "riot ten",
    "ivory ",
    "bear grillz",
    "trollphace",
    "kayzo ",
    "kai wachi",
    "midnight tyrannosaurus",
    "aweminus",
    "jantsen",
    "vastive",
    "yakz ",
    "adventure club",
    "the frim",
    "peekaboo dubstep", "peekaboo ",
    "level up dubstep",
    "boombox cartel",
    "wolfgang gartner",
    "rickyxsan",
    "svdxn",
    "monxx",
    "ray volpe",
    "g-rex", "g rex",
    "modestep",
    "megalodon dubstep",
    "of the trees dubstep",
    "hydraulix",
    "space chunk",
    "sullivan king",
    "conrank",
    "steve aoki dubstep",
    "excision presents",
    "12th planet presents",
    "distinct dubstep",
    "dieselboy",
    "jauz dubstep",
    "figure ",
    "griz dubstep",
    "trollphace remix",
    "seven lions dubstep",
    # ─ Genre terms ─
    "dubstep", "brostep",
    "riddim ",
    "wobble bass",
    "140 bass", "140bpm bass",
    "melodic dubstep",
    "deathstep",
    "tearout",
    "future riddim",
    "dub step",
    "dubstep remix",
    "heavy bass drop",
]

TRAP_TWERK_KEYWORDS = [
    # ─ Trap / hip-hop crossover artists ─
    "migos",
    "travis scott",
    "future ",
    "gucci mane",
    "21 savage",
    "lil uzi vert",
    "playboi carti",
    "metro boomin",
    "lil jon",
    "waka flocka",
    "rae sremmurd",
    "baauer",
    "rl grime",
    "flosstradamus",
    "quality control",
    "chief keef",
    "young thug",
    "gunna ",
    "lil baby",
    "desiigner",
    "smokepurpp",
    "ski mask the slump god",
    "trippie redd",
    "yung gravy",
    "tyga ",
    # ─ Jersey club / juke ─
    "uniiqu3",
    "jersey club kingz",
    "dj sliink",
    "dj tameil",
    "rl grime jersey",
    "dj funk",
    "dj rashad",
    "dj spinn",
    "traxman",
    "dj clent",
    "cash cash trap",
    "lex luger",
    "zaytoven",
    "southside 808 mafia", "808 mafia",
    "tay keith",
    "murda beatz",
    "wheezy ",
    "young chop",
    "mike will made it",
    "dj esco",
    "gucci mane trap",
    "lil pump",
    "smokepurpp trap",
    "ronny j",
    "internet money",
    "sfera ebbasta",
    "trap city",
    "sremm life",
    "quality control music",
    "chief keef trap",
    "lil durk",
    "king von",
    "moneybagg yo",
    "pooh shiesty",
    "42 dugg",
    "roddy ricch",
    "nardo wick",
    "dababy trap",
    "megan thee stallion trap",
    # ─ Genre terms ─
    "trap ", "trap music",
    "twerk ",
    "jersey club",
    "juke ", "footwork",
    "booty bounce", "booty music",
    "percolate ",
    "drill ", "uk drill", "brooklyn drill",
    "phonk ", "memphis phonk",
    "hyphy ",
    "crunk ",
    "trap remix",
    "twerk anthem",
]

GLOBAL_BASS_KEYWORDS = [
    # ─ Global bass / baile funk artists ─
    "anitta",
    "santo & avance", "santo and avance",
    "major lazer",
    "diplo ",
    "dillon francis",
    "mc fioti",
    "alok ",
    "pedro sampaio",
    "kevinho",
    "ludmilla",
    "mc gw",
    "mc kevin o chris",
    "os hawaianos",
    "putumayo",
    "quantic",
    "nickodemus",
    "sidestepper",
    "buraka som sistema",
    "dj marlboro",
    "bonde do role", "bonde do rolê",
    "deize tigrona",
    # ─ Moombahton / guaracha artists ─
    "dj sonko",
    "munchi ",
    "chuckie moombahton",
    "sango ",
    "the geeksta",
    "dj snake tribal",
    "matroda",
    "yaleidys",
    "brian cross",
    "javi mula",
    "dj rockwell guaracha",
    "el guincho",
    "sidney samson moombahton",
    "afrojack moombahton",
    "dj laz",
    "flosstradamus global",
    "uproot andy",
    "señor coconut", "senor coconut",
    "beto perez zumba",
    "mad decent",
    "dillon francis moombahton",
    "walshy fire",
    "the geeksta moombahton",
    "kartel dembow",
    "el alfa",
    "chimbala",
    "bulova dembow",
    "rochy rd",
    "dembow dominicano",
    "afro bros",
    "dj snake global",
    "carnaval mix",
    "batidão", "batidao",
    "tribal guarachero mix",
    "guaracha 2023",
    "electro guaracha",
    "afterparty guaracha",
    "3ball mty",
    # ─ Genre terms ─
    "baile funk", "funk brasil", "funk brasileiro", "funk carioca",
    "moombahton",
    "dembow ",
    "global bass",
    "favela funk",
    "brazilian funk",
    "guaracha ",
    "tribal guarachero", "tribal house mexicano",
    "afro house crossover",
    "3ball", "tribal mtl",
    "kuduro ",
    "afrobeat bass",
    "world club",
]

DISCO_NUDISCO_KEYWORDS = [
    # ─ Classic disco artists ─
    "bee gees",
    "chic ",
    "nile rodgers",
    "donna summer",
    "earth wind & fire", "earth wind and fire",
    "kool & the gang", "kool and the gang",
    "sister sledge",
    "the trammps", "trammps ",
    "gloria gaynor",
    "abba ",
    "village people",
    "kc and the sunshine band", "kc & the sunshine band",
    "boney m",
    "thelma houston",
    "gwen mccrae",
    "yvonne elliman",
    "cerrone ",
    "patrick hernandez",
    "vicki sue robinson",
    # ─ Nu-disco / indie dance ─
    "purple disco machine",
    "dimitri from paris",
    "todd terje",
    "daft punk",
    "justice ",
    "breakbot",
    "roisin murphy", "róisín murphy",
    "jungle ",
    "chromeo ",
    "the whitest boy alive",
    "metronomy",
    "hercules and love affair", "hercules & love affair",
    "classixx",
    "mark ronson",
    "goldroom",
    "these are my jams",
    "crazy p",
    "aeroplane ",
    "yuksek ",
    "riva starr",
    "purple fusion",
    "moon boots",
    "franc moody",
    "sault ",
    "tensnake",
    "aeon boy",
    "cassius ",
    "space cowboy",
    "sister sledge disco",
    "shalamar",
    "change band",
    "gloria estefan disco",
    "the gap band",
    "rose royce",
    "gino soccio",
    "voyage disco",
    "amii stewart",
    # ─ Genre terms ─
    "disco ", "disco classic",
    "nu disco", "nu-disco",
    "italo disco", "italo ",
    "french house",
    "filter house",
    "indie dance",
    "boogie ", "post-disco", "post disco",
    "discotheque",
    "space disco",
    "cosmic disco",
    "disco edit",
    "hi-nrg disco", "hi nrg disco",
]

NUMETAL_KEYWORDS = [
    # ─ Nu-metal / rap-rock artists ─
    "linkin park",
    "limp bizkit",
    "korn ",
    "deftones",
    "system of a down",
    "rage against the machine",
    "papa roach",
    "slipknot",
    "p.o.d.", "p.o.d ",
    "static-x", "static x",
    "disturbed",
    "evanescence",
    "rammstein",
    "drowning pool",
    "godsmack",
    "mudvayne",
    "soulfly",
    "staind",
    "incubus",
    "alien ant farm",
    "bloodhound gang",
    "crazy town",
    "the prodigy",
    "sevendust",
    "coal chamber",
    "orgy ",
    "spineshank",
    "adema",
    "taproot",
    "cold ",
    "3 doors down", "three doors down",
    "puddle of mudd",
    "trapt",
    "hoobastank",
    "saliva ",
    "flaw ",
    "nonpoint",
    "ill nino", "ill niño",
    "chevelle",
    "shinedown",
    "breaking benjamin",
    "seether",
    "hollywood undead",
    "papa roach infest",
    "korn issues",
    "deftones white pony",
    "system of a down toxicity",
    "linkin park hybrid theory",
    "slipknot iowa",
    "disturbed sickness",
    "godsmack awake",
    "drowning pool sinner",
    "static-x wisconsin",
    "mudvayne ld 50",
    "spineshank height",
    "soulfly primitive",
    "10 years band",
    "p.o.d southtown",
    "cold year of the spider",
    "flaw through the eyes",
    "trapt headstrong",
    "puddle of mudd blurry",
    "otep ",
    "sevendust animosity",
    "adema unstable",
    "taproot gift",
    # ─ Genre / era terms ─
    "nu metal", "nu-metal",
    "rap rock", "rap-rock",
    "rapcore",
    "alt metal", "alternative metal",
    "groove metal wave",
    "family values tour",
    "ozzfest",
]

MASHUP_KEYWORDS = [
    # ─ Mashup / edit producers and crews ─
    "kill mr dj", "kill mr. dj",
    "djs from mars",
    "dj cummerbund",
    "kill paris",
    "eskei83",
    "morty ",
    "samurai edit", "samurai remix",
    "da brozz",
    "djenergy",
    "justera",
    "hogzz",
    "nath jennings",
    "dj vince",
    "mashup germany",
    "toy selectah",
    "mightyfools",
    "arman cekin",
    "wh0 mashup",
    "ambrose ",
    "mashupmix",
    "party favor edit",
    "dj lobo",
    "supreme team edits",
    "jerome price",
    "cash cash mashup",
    "dj thera",
    "twiins edits",
    "mvrk edits",
    "ryan skyy edits",
    "runaway december edits",
    "dj xd edits",
    "vdj vantage",
    "mashup nation",
    "clean transition pack",
    "party starter edit",
    "reggaeton to house transition",
    "hip hop to house transition",
    "genre bending edit",
    "quick mix edit",
    "wedding mashup pack",
    "hype intro pack",
    "bpm matched edit",
    "acapella mashup",
    "dirty edit",
    "instrumental edit pack",
    "vip edit",
    "moombahton edit",
    "extended edit pack",
    "festival mashup",
    "carnival mashup",
    # ─ Genre / process terms ─
    "mashup ", "mash up ", "mash-up",
    "bootleg mix", "bootleg edit",
    " vs. ", " vs ",
    "blend edit", "dj blend",
    "edit pack",
    "flip edit", "hype flip",
    "refix ",
    "rework edit",
    "transition edit",
    "quick hit edit", "quick-hit edit",
    "short edit",
    "intro edit", "clean intro edit",
    "acapella out", "acapella in",
    "open format edit", "open-format edit",
    "wedding edit",
    "hype edit",
    "clean edit",
    "smash-up",
]

EIGHTIES_KEYWORDS = [
    # ─ 1980s artists ─
    "michael jackson",
    "madonna ",
    "prince ",
    "whitney houston",
    "george michael",
    "wham!", "wham ",
    "a-ha ", "a ha ",
    "depeche mode",
    "new order",
    "cyndi lauper",
    "tears for fears",
    "toto ",
    "bonnie tyler",
    "duran duran",
    "culture club",
    "hall & oates", "hall and oates",
    "billy idol",
    "rick astley",
    "blondie ",
    "queen ",
    "eurythmics",
    "talking heads",
    "inxs ",
    "the police",
    "phil collins",
    "genesis ",
    "peter gabriel",
    "simple minds",
    "human league",
    "spandau ballet",
    "pet shop boys",
    "the b-52's", "the b-52s",
    "kim wilde",
    "irene cara",
    "kenny loggins",
    "huey lewis",
    "chaka khan",
    "lionel richie",
    "kool & the gang eighties",
    "starship ",
    "berlin ",
    "the outfield",
    "the cars",
    "devo ",
    "yazoo",
    "howard jones",
    "level 42",
    "bananarama",
    "chris de burgh",
    "van halen",
    "journey ",
    "foreigner",
    "survivor ",
    "the go-go's", "the go gos",
    "the psychedelic furs",
    "orchestral manoeuvres", "modern english",
    "naked eyes",
    "til tuesday", "'til tuesday",
    "animotion",
    "book of love",
    "when in rome band",
    "flock of seagulls",
    "men at work",
    "thompson twins",
    "the fixx",
    # ─ Genre terms ─
    "80s ", "eighties",
    "new wave",
    "synthpop", "synth pop",
    "80s power ballad",
    "80s dance classic",
    "80s freestyle",
    "80s remix",
]

NINETIES_KEYWORDS = [
    # ─ 1990s pop / eurodance artists ─
    "spice girls",
    "backstreet boys",
    "nsync", "n sync",
    "britney spears",
    "ricky martin",
    "aqua ",
    "vengaboys",
    "ace of base",
    "haddaway",
    "dr alban", "dr. alban",
    "corona ",
    "2 unlimited", "two unlimited",
    "snap! ", "snap ",
    "la bouche",
    "real mccoy",
    "culture beat",
    "robin s ", "robin s. ",
    "crystal waters",
    "c+c music factory", "c and c music factory",
    "whigfield",
    "gala ",
    "eiffel 65",
    "cappella ",
    "twenty 4 seven",
    "alexia ",
    "livin joy",
    "black box",
    "technotronic",
    "mr president",
    "captain jack",
    "dj bobo",
    "no mercy",
    "jamiroquai",
    "salt-n-pepa", "salt n pepa",
    "en vogue",
    "coolio ",
    "sir mix-a-lot",
    "vanilla ice",
    "mc hammer",
    "los del rio",
    "los del río",
    "run-d.m.c. 90s",
    "montell jordan",
    "next 90s",
    "702 group",
    "brandy 90s",
    "monica 90s",
    "az yet",
    "blackstreet",
    "boyz ii men",
    "all-4-one", "all 4 one",
    "color me badd",
    "shai band",
    "jodeci",
    "silk band",
    "sweetbox",
    "real to reel", "real 2 real",
    "amber ",
    "dj miko",
    "masterboy",
    "praga khan",
    "opus iii", "opus 3",
    "cappella u got 2 know",
    "sash!", "sash ",
    # ─ Genre terms ─
    "90s ", "nineties",
    "eurodance",
    "handbag house",
    "90s dance classic",
    "90s eurodance",
    "90s club anthem",
    "90s freestyle",
]

TWOTHOUSANDS_KEYWORDS = [
    # ─ 2000s pop / club artists ─
    "rihanna",
    "beyonce", "beyoncé",
    "usher ",
    "nelly ",
    "pitbull ",
    "black eyed peas",
    "lady gaga",
    "ke$ha", "kesha",
    "david guetta",
    "flo rida",
    "akon ",
    "timbaland",
    "justin timberlake",
    "sean paul",
    "shaggy ",
    "chris brown",
    "ne-yo", "ne yo",
    "t-pain", "t pain",
    "lumidee",
    "cascada",
    "basshunter",
    "kelly clarkson",
    "christina aguilera",
    "gwen stefani",
    "fergie ",
    "jason derulo",
    "sean kingston",
    "soulja boy",
    "outkast",
    "missy elliott",
    "destiny's child", "destinys child",
    "3 doors down 2000s",
    "avril lavigne",
    "the pussycat dolls", "pussycat dolls",
    "maroon 5",
    "one republic", "onerepublic",
    "shakira ",
    "enrique iglesias",
    "yolanda be cool",
    "britney spears 2000s",
    "christina milian",
    "ashanti ",
    "amerie ",
    "ciara 2000s",
    "omarion",
    "chris brown 2000s",
    "sean paul 2000s",
    "wyclef jean 2000s",
    "shaggy 2000s",
    "baha men",
    "eiffel 65 2000s",
    "d12 2000s",
    "bowling for soup",
    "simple plan",
    "good charlotte",
    "yellowcard",
    "the click five",
    "vanessa carlton",
    "michelle branch",
    "jesse mccartney",
    "aly & aj", "aly and aj",
    "cascada 2000s",
    # ─ Genre / era terms ─
    "2000s ", "00s ",
    "noughties",
    "electro house 2008",
    "club banger",
    "2000s club anthem",
    "2000s throwback",
    "y2k pop",
    "crunk 2000s",
]

DEEP_MELODIC_HOUSE_KEYWORDS = [
    # ─ Deep / melodic / progressive house artists ─
    "lane 8",
    "ben bohmer", "ben böhmer",
    "rufus du sol", "rüfüs du sol",
    "tinlicker",
    "yotto ",
    "nora en pure",
    "monolink",
    "bedouin ",
    "adriatique",
    "tale of us",
    "kolsch", "kölsch",
    "maribou state",
    "bonobo ",
    "cristoph deep",
    "yubik",
    "jerro ",
    "sofi tukker",
    "goldcap",
    "jan blomqvist",
    "chris avantgarde",
    "innellea",
    "massano",
    "mind against",
    "recondite",
    "dosem",
    "marsh ",
    "dennis ferrer",
    "sultan + shepard",
    "gorje hewek",
    "andrew bayer melodic",
    "eli & fur", "eli and fur",
    "cassian ",
    "hunter/game", "hunter game",
    "stephan bodzin",
    "âme ", "dixon ",
    "solomun ",
    "hernan cattaneo",
    "nick warren",
    "guy j",
    "einmusik",
    "worakls",
    "michael canitrot",
    "sonja moonear",
    "bob moses",
    "sasha carassi",
    "monolink deep",
    "the blaze",
    "cristoph et al",
    "jerro melodic",
    "artbat",
    "meduza melodic",
    "cassian remix",
    "westend melodic",
    "hunter game melodic",
    "sonja moonear deep",
    "guy j deep",
    "microtrauma",
    # ─ Labels ─
    "anjunadeep",
    "afterlife records",
    "all day i dream",
    "colorize records",
    "get physical",
    "sincopat",
    # ─ Genre / event terms ─
    "deep house", "melodic house",
    "progressive house",
    "organic house",
    "afterlife set",
    "sunset set",
    "melodic techno set",
    "desert melodic",
    "downtempo melodic house",
]

AFRO_HOUSE_KEYWORDS = [
    # ─ Afro house / afro tech artists ─
    "black coffee",
    "keinemusik",
    "&me ", "and me house",
    "rampa ",
    "adam port",
    "themba ",
    "shimza",
    "da capo",
    "culoe de song",
    "caiiro",
    "enoo napa",
    "msaki",
    "kususa",
    "vinny da vinci",
    "black motion",
    "prince kaybee",
    "de mogul sa",
    "sun-el musician", "sun el musician",
    "jullian gomes",
    "zakes bantwini",
    "fka mash",
    "argy afro",
    "gaba cannal",
    "shona sax",
    "kim johannson",
    "atmos blaq",
    "manoo ",
    "osunlade",
    "toshi ",
    "diephuis",
    "franc kissi",
    "khoisan",
    "bafana ",
    "citizen deep",
    "mörda", "morda ",
    "boddhi satva",
    "black coffee presents",
    "themba afro",
    "de capo",
    "black motion presents",
    "dj maphorisa afro house",
    "kabza de small afro house",
    "kususa deep",
    "fka mash afro",
    "shimza presents",
    "muzi ",
    "buddynice",
    "distruction boyz",
    "dbn gogo",
    "tresor afro",
    "vigro deep afro",
    "mr jazziq",
    "kelvin momo",
    "lady du",
    "young stunna",
    "nkosazana daughter",
    "murumba pitch",
    "josiah de disciple",
    "team mosha",
    "mafikizolo",
    "toshi bumpa",
    "juzior",
    "afriikan roots",
    "citizen boy",
    "el mundo afro",
    "argy afro tech",
    "sultan and shepard afro",
    "goldfish band",
    "black coffee live",
    # ─ Genre terms ─
    "afro house", "afro tech",
    "3step ", "3-step house",
    "tribal house afro",
    "sunset afro set",
    "afro deep",
    "afro tribal",
]

HARD_DANCE_KEYWORDS = [
    # ─ Hardstyle / hardcore artists ─
    "headhunterz",
    "da tweekaz",
    "sub zero project",
    "wildstylez",
    "angerfist",
    "d-block & s-te-fan", "d-block and s-te-fan",
    "brennan heart",
    "coone ",
    "rebelion",
    "warface",
    "atmozfears",
    "phuture noize",
    "b-front", "b front",
    "adaro ",
    "digital punk",
    "ran-d", "ran d",
    "code black",
    "sound rush",
    "vertile",
    "malice ",
    "audiotricz",
    "frontliner",
    "isaac ",
    "act of rage",
    "regain",
    "toneshifterz",
    "the prophet hardstyle",
    "korsakoff",
    "the pitcher",
    "endymion",
    "partyraiser",
    "n-vitral", "n vitral",
    "sefa ",
    "gunz for hire",
    "sound rush and da tweekaz",
    "crypsis",
    "d-sturb", "d sturb",
    "villain hardstyle",
    "radical redemption",
    "geck-o", "geck o",
    "psyko punkz",
    "devin wild",
    "eugenio tokarev",
    "b-freqz", "b freqz",
    "showtek hardstyle",
    "noisecontrollers",
    "zatox",
    "sub sonik",
    "the sickest squad",
    "delete hardstyle",
    "meccano twins",
    "technoboy",
    "dj neophyte",
    "the pitcher rawstyle",
    "coone and da tweekaz",
    "audiofreq",
    "outbreak of evil",
    "sefa and marc storm",
    "krewella hardstyle",
    "wildstylez and the prophet",
    "toneshifterz and ncr",
    "hard dance nation",
    "q-dance", "qdance",
    "defqon 1",
    # ─ Genre terms ─
    "hardstyle", "hardcore", "rawstyle",
    "hard techno",
    "gabber ",
    "uptempo hardcore",
    "euphoric hardstyle",
    "reverse bass",
    "freeform ",
    "terror hardcore",
    "jumpstyle",
]

DRILL_KEYWORDS = [
    # ─ Drill artists ─
    "central cee",
    "headie one",
    "digga d",
    "pop smoke",
    "fivio foreign",
    "sheff g",
    "unknown t",
    "russ millions",
    "arrdee",
    "k-trap", "k trap",
    "harlem spartans",
    "1011 drill", "410 drill",
    "loski ",
    "abra cadabra",
    "russ ",
    "ny drill collective",
    "bandokay",
    "aitch drill",
    "meekz",
    "dutchavelli",
    "digga d and the",
    "ohgeesy",
    "bizness drill",
    "kwengface",
    "og hoodstarz",
    "22gz ",
    "270 fully",
    "b-lovee", "b lovee",
    "eli fross",
    "dougie b",
    "sha ek",
    "fivio foreign drill",
    "pop smoke woo",
    "central cee drill",
    "headie one edna",
    "digga d chingford",
    "unknown t drillers",
    "russ millions body",
    "aitch and central cee",
    "stormzy drill",
    "dave drill",
    "krept and konan",
    "nines drill",
    "ghetts drill",
    "wretch 32 drill",
    "not3s drill",
    "abra cadabra dna",
    "harlem spartans zone 2",
    "sl woo drill",
    "loski zone 2",
    "clavish",
    "poundz",
    "aggy virus",
    "carns hill",
    "mixtape madness drill",
    "ny drill scene",
    "22gz sniper gang",
    "jenn carter drill",
    "sha ek and jenn carter",
    "fivio foreign zoo",
    "coi leray drill",
    "kay flock",
    "dougie b drill",
    "bandmanrill",
    "wet drill",
    "ny drill remix",
    "drill instrumental",
    "sample drill",
    # ─ Genre terms ─
    "uk drill", "ny drill", "brooklyn drill",
    "drill remix",
    "drill beat",
    "chicago drill",
    "afro drill",
    "italian drill",
]

BALKAN_GYPSY_KEYWORDS = [
    # ─ Balkan / gypsy artists ─
    "goran bregovic",
    "emir kusturica",
    "fanfare ciocarlia",
    "taraf de haidouks",
    "shantel ",
    "balkan beat box",
    "dubioza kolektiv",
    "gogol bordello",
    "boban markovic",
    "no smoking orchestra",
    "beirut band",
    "koby israelite",
    "besh o drom",
    "mahala rai banda",
    "zlatne uste",
    "amsterdam klezmer band",
    "romano drom",
    "brave old world",
    "yuri yunakov",
    "ivo papasov",
    "esma redzepova", "esma redžepova",
    "shukar collective",
    "orkestar bez ime",
    "opa cupa",
    "romengo",
    "vera bila",
    "kolo ansambl",
    "veselin plakalović",
    "jony iliev",
    "boris kovac",
    "vlado kumpan",
    "guca trumpet festival",
    "trumpet summit balkan",
    "romano suno",
    "the debutante balkan",
    "zeneli brass band",
    "balkanika",
    "kalinka band",
    "fanfare shqiptare",
    "farafina brass",
    "orkestar loco",
    "gogol bordello live",
    "shantel bucovina",
    "koby israelite live",
    "besh o drom live",
    "hazmat modine",
    "9 horses",
    "romani rose ensemble",
    "amsterdam klezmer band live",
    "yiddish twist orchestra",
    "los desterrados",
    "orkestar slivovica",
    "brass band gypsy fest",
    "voodoo hop balkan",
    "fanfare balkanika",
    "bulgarian voices balkan",
    "gogol bordello wonderlust",
    "dubioza kolektiv live",
    "no smoking orchestra live",
    "romano drom live",
    "zeneli",
    "mahala rai banda live",
    "kal band live",
    "besh o drom brass",
    "sziget balkan",
    "guca festival brass",
    # ─ Genre terms ─
    "balkan brass", "balkan beats",
    "gypsy brass", "gypsy punk",
    "klezmer ",
    "brass band balkan",
    "hora ", "kolo dance",
    "tarantella",
    "oriental brass band",
    "romani music",
    "chalga",
]

WORLD_ETHNIC_KEYWORDS = [
    # ─ World / ethnic artists ─
    "idan raichel",
    "ali farka toure", "ali farka touré",
    "tinariwen",
    "buena vista social club",
    "fela kuti",
    "rachid taha",
    "omar souleyman",
    "vieux farka toure",
    "youssou n'dour", "youssou ndour",
    "salif keita",
    "cesaria evora", "cesária évora",
    "manu chao",
    "amr diab",
    "nancy ajram",
    "haifa wehbe",
    "tarkan ",
    "sezen aksu",
    "mustafa sandal",
    "ravi shankar",
    "nusrat fateh ali khan",
    "a r rahman", "a.r. rahman",
    "shreya ghoshal",
    "arijit singh",
    "mahmoud darwish",
    "fairuz ", "fayrouz",
    "umm kulthum",
    "vicente amigo",
    "paco de lucia", "paco de lucía",
    "gipsy kings",
    "buika ",
    "estrella morente",
    "the chieftains",
    "clannad ",
    "enya ",
    "runrig ",
    "flook ",
    "aterciopelados",
    "susana baca",
    "toto la momposina",
    "orchestra baobab",
    "tabu ley rochereau",
    "franco luambo",
    "angelique kidjo", "angélique kidjo",
    "mariza ",
    "cheb khaled",
    "natacha atlas",
    "khaled ", "cheb mami",
    "dj khalab",
    "hindi zahra",
    "mory kante",
    "toumani diabate world",
    "ravi shankar sitar",
    "trilok gurtu",
    "zakir hussain tabla",
    "yungchen lhamo",
    "sainkho namtchylak",
    "vusi mahlasela",
    # ─ Genre terms ─
    "greek laika", "rebetiko",
    "turkish pop",
    "bollywood ",
    "ethiopian jazz", "ethio jazz",
    "flamenco ", "nuevo flamenco",
    "celtic music",
    "bhangra ",
    "rai music", "raï music",
    "gnawa ",
    "cumbia folk",
    "fado ",
    "afrobeat classic",
]

ECSTATIC_CEREMONY_KEYWORDS = [
    # ─ Ecstatic dance / ceremony artists ─
    "desert dwellers",
    "kalya scintilla",
    "equanimous",
    "shpongle ceremony",
    "clozee",
    "beats antique",
    "random rab",
    "liquid bloom",
    "porangui", "poranguí",
    "deya dova",
    "ayla nereo",
    "nadav mikaeli",
    "sam haft",
    "bird of paradise",
    "michael dunphy",
    "j'attend",
    "gaudi ",
    "sonic species",
    "gaia ",
    "guy mendilow",
    "sacred earth music",
    "cloudchord",
    "govinda ",
    "michael manring",
    "wildlight",
    "mosaic tribe",
    "seven directions",
    "trevor hall",
    "bhakti brothers",
    "peia ",
    "nikola dosen",
    "east forest",
    "moksha music",
    "one world tribe",
    "wild belle ceremony",
    "aes dana",
    "entheogenic",
    "atash ",
    "sina ",
    "delhi 2 dublin ceremony",
    "beautiful chorus",
    "lulacruza",
    "hibiscus dream",
    "yaima ",
    "rising appalachia",
    "nahko and medicine for the people", "nahko & medicine for the people",
    "xavier rudd ceremony",
    "trevor hall ceremony",
    "michael franti ceremony",
    "beautiful chorus tribe",
    "mamuse ",
    "peia moon tribe",
    "how hou",
    "delhi sultanate",
    "kaminanda",
    "one world ceremony",
    "sacred tribe collective",
    "the polish ambassador",
    "govinda live",
    "desert hearts family",
    "shamanic breathwork",
    "sound bath ceremony",
    "yoni ceremony",
    "cacao and sound",
    # ─ Genre / event terms ─
    "ecstatic dance",
    "ceremony set", "ceremony music",
    "medicine music",
    "sacred fire",
    "shamanic journey",
    "cacao ceremony",
    "kirtan ",
    "mantra chant",
    "conscious dance",
    "journey set",
    "temple space",
    "breathwork music",
    "womb ceremony",
]

CHILL_DOWNTEMPO_KEYWORDS = [
    # ─ Chill / downtempo / lounge artists ─
    "thievery corporation",
    "zero 7",
    "air duo",
    "massive attack",
    "portishead",
    "emancipator",
    "tycho ",
    "nujabes",
    "parov stelar",
    "st germain", "st. germain",
    "gotan project",
    "kruder & dorfmeister", "kruder and dorfmeister",
    "jose gonzalez", "josé gonzález",
    "nightmares on wax",
    "bonobo chill",
    "cinematic orchestra",
    "royksopp", "röyksopp",
    "boozoo bajou",
    "afterlife chill",
    "hooverphonic",
    "morcheeba",
    "olive ",
    "zero-g lounge",
    "brand new heavies",
    "koop ",
    "khruangbin",
    "yppah",
    "bohren & der club of gore",
    "wax tailor",
    "blockhead ",
    "bexta ",
    "mr scruff", "mr. scruff",
    "kaya project",
    "jaia ",
    "hidden orchestra",
    "zero 7 simple things",
    "air moon safari",
    "thievery corporation sounds",
    "de-phazz", "de phazz",
    "les gordon",
    "kaya project chill",
    "lemongrass chill",
    "buddha bar",
    "hotel costes",
    "cafe del mar",
    "nicola conte",
    "jazzanova",
    "gilles peterson",
    "brownswood recordings",
    "arnaud rebotini chill",
    "bobby mcferrin",
    "jamie woon",
    "james blake chill",
    "little dragon",
    "poolside chill",
    "washed out",
    "chromatics",
    "boards of canada chill",
    "emancipator society",
    # ─ Genre / setting terms ─
    "downtempo", "chillout", "chill out",
    "lounge music",
    "trip hop", "trip-hop",
    "nu jazz",
    "acoustic cover",
    "bossa nova cover",
    "ambient chill",
    "dinner set",
    "cocktail hour",
    "sunset lounge",
    "smooth jazz chill",
]

INDIE_ALTPOP_KEYWORDS = [
    # ─ Indie / alt-pop artists ─
    "arctic monkeys",
    "the killers",
    "franz ferdinand",
    "kings of leon",
    "mgmt ",
    "foster the people",
    "two door cinema club",
    "phoenix band",
    "vampire weekend",
    "glass animals",
    "tame impala",
    "empire of the sun",
    "hot chip",
    "lcd soundsystem",
    "caribou ",
    "jungle band", "jungle - ",
    "fred again..", "fred again",
    "bon iver",
    "alt-j", "alt j",
    "the 1975",
    "declan mckenna",
    "wolf alice",
    "sports team",
    "fontaines d.c.", "fontaines dc",
    "idles ",
    "gang of youths",
    "spoon band",
    "grizzly bear",
    "local natives",
    "the war on drugs",
    "band of horses",
    "cage the elephant indie",
    "milky chance",
    "young the giant",
    "walk the moon indie",
    "portugal the man",
    "st vincent", "st. vincent",
    "beach house",
    "chvrches",
    "the japanese house",
    "still woozy indie",
    "surf curse indie",
    "current joys",
    "the strokes indie",
    "franz ferdinand takeaway",
    "kaiser chiefs indie",
    "the vaccines",
    "peace band",
    "swim deep",
    "temples band",
    "the districts",
    "hippo campus",
    "coin band",
    "the aces band",
    "wallows ",
    "clairo indie",
    "beach bunny",
    "boy pablo",
    "cavetown",
    "dayglow",
    "role model musician",
    "gus dapperton",
    "still woozy",
    "rex orange county indie",
    "the marias indie", "the marías indie",
    "faye webster",
    "briston maroney",
    "peach pit",
    # ─ Genre terms ─
    "indie pop", "indie-pop", "alt pop", "alt-pop",
    "indie rock anthem",
    "festival indie",
    "indie disco",
]

OLDIES_MOTOWN_KEYWORDS = [
    # ─ Oldies / Motown / early soul artists ─
    "elvis presley",
    "chuck berry",
    "little richard",
    "the beatles",
    "the supremes",
    "marvin gaye",
    "stevie wonder",
    "the temptations",
    "aretha franklin",
    "ray charles",
    "sam cooke",
    "otis redding",
    "ben e king", "ben e. king",
    "the ronettes",
    "frank sinatra",
    "dean martin",
    "the four tops", "four tops",
    "smokey robinson",
    "the miracles",
    "martha and the vandellas", "martha & the vandellas",
    "the shirelles",
    "the drifters",
    "the platters",
    "buddy holly",
    "roy orbison",
    "the everly brothers",
    "connie francis",
    "brenda lee",
    "sam & dave", "sam and dave",
    "wilson pickett oldies",
    "percy sledge",
    "the isley brothers",
    "jackie wilson",
    "dusty springfield",
    "petula clark",
    "the crystals",
    "the shangri-las",
    "dionne warwick",
    "nat king cole",
    "louis armstrong",
    "bill haley",
    "the platters oldies",
    "gene chandler",
    "the marvelettes",
    "junior walker",
    "edwin starr",
    "the contours",
    "mary wells",
    "the velvelettes",
    "kim weston",
    "brenda holloway",
    "tammi terrell",
    "the spinners motown",
    "rare earth band",
    "the elgins",
    "the originals motown",
    "bobby vinton",
    "neil sedaka",
    "paul anka",
    "frankie valli", "the four seasons",
    "the righteous brothers",
    "the mamas and the papas",
    "the turtles",
    # ─ Genre / era terms ─
    "motown classic",
    "doo wop", "doo-wop", "doowop",
    "rock and roll oldie", "rock 'n' roll",
    "rockabilly classic",
    "50s hit", "fifties hit",
    "60s hit", "sixties hit",
    "oldies but goodies",
    "sock hop",
]

RNB_SOUL_MODERN_KEYWORDS = [
    # ─ Modern R&B / neo-soul artists ─
    "sza ",
    "frank ocean",
    "the weeknd", "weeknd",
    "daniel caesar",
    "h.e.r.", "her music",
    "jhene aiko", "jhené aiko",
    "summer walker",
    "giveon ",
    "anderson .paak", "anderson paak",
    "erykah badu",
    "d'angelo", "dangelo",
    "alicia keys",
    "miguel ",
    "tyla ",
    "cleo sol",
    "brent faiyaz",
    "kehlani ",
    "khalid ",
    "bryson tiller",
    "6lack",
    "jorja smith",
    "lucky daye",
    "ari lennox",
    "muni long",
    "chris brown modern rnb",
    "victoria monet", "victoria monét",
    "snoh aalegra",
    "leon bridges",
    "raveena",
    "sabrina claudio",
    "jessie reyez",
    "the internet band",
    "steve lacy",
    "ravyn lenae",
    "yebba ",
    "mahalia rnb",
    "queen naija",
    "kaash paige",
    "ella mai",
    "jazmine sullivan",
    "kali uchis",
    "amber mark",
    "bilal ",
    "maxwell rnb",
    "musiq soulchild modern",
    "goapele",
    "eric bellinger",
    "trey songz modern",
    "jeremih",
    "the weeknd starboy",
    "frank ocean blonde",
    "sza ctrl",
    "daniel caesar freudian",
    "h.e.r. album",
    "summer walker over it",
    "giveon take time",
    "brent faiyaz larger than life",
    "lucky daye painted",
    "ari lennox shea butter baby",
    "kehlani sweetsexysavage",
    "tinashe modern rnb",
    "teyana taylor modern",
    "mahalia love and compromise",
    "queen naija album",
    # ─ Genre terms ─
    "modern rnb", "r&b modern",
    "neo soul", "neo-soul",
    "slow jam",
    "bedroom rnb", "bedroom r&b",
    "alt rnb", "alternative rnb",
]

WEDDING_CEREMONY_KEYWORDS = [
    # ─ Ceremony / romantic terms and titles ─
    "first dance",
    "wedding processional",
    "processional song",
    "recessional song",
    "canon in d",
    "ave maria",
    "hallelujah cohen", "hallelujah wedding",
    "a thousand years",
    "perfect ed sheeran",
    "at last etta james", "at last - etta james",
    "thinking out loud",
    "marry you bruno mars",
    "chuppah music",
    "romantic slow dance",
    "acoustic wedding cover",
    "string quartet cover",
    "piano wedding cover",
    "slow dance song",
    "love ballad",
    "bridal entrance",
    "wedding march",
    "here comes the bride",
    "make you feel my love",
    "all of me john legend",
    "wonderful tonight",
    "everything i do i do it for you",
    "unchained melody",
    "can't help falling in love",
    "you are the reason",
    "speechless jonas brothers",
    "grow old with you",
    "your song elton john",
    "the vow music",
    "signed sealed delivered wedding",
    "forever ben harper wedding",
    "i choose you",
    "wedding entrance song",
    "father daughter dance",
    "mother son dance",
    "wedding ceremony playlist",
    "wedding vows music",
    "ring exchange song",
    "unity candle song",
    "sand ceremony song",
    "wedding officiant music",
    "aisle walk song",
    "bridal party entrance",
    "groomsmen entrance",
    "wedding cocktail hour music",
    "wedding reception entrance",
    "cake cutting song",
    "bouquet toss song",
    "garter toss song",
    "last dance wedding",
    "wedding exit song",
    "sparkler exit song",
    "elton john your song",
    "etta james at last",
    "israel kamakawiwoole over the rainbow", "iz over the rainbow",
    "the way you look tonight",
    "l-o-v-e nat king cole",
    "stand by me wedding",
    "in my life beatles wedding",
    "i will always love you wedding",
    "when you say nothing at all",
    "just the way you are bruno mars",
    "better together jack johnson wedding",
    "budapest george ezra wedding",
    "how long will i love you",
    "iris goo goo dolls wedding",
    "yellow coldplay wedding",
    "harvest moon wedding",
    "amazed lonestar",
    "vince gill look at us",
    "kiss from a rose wedding",
    "everything wedding song",
    "you and me lifehouse wedding",
]

OPENFORMAT_KEYWORDS = {
    "techno": TECHNO_KEYWORDS,
    "trance": TRANCE_KEYWORDS,
    "dubstep": DUBSTEP_KEYWORDS,
    "trap_twerk": TRAP_TWERK_KEYWORDS,
    "global_bass": GLOBAL_BASS_KEYWORDS,
    "disco_nudisco": DISCO_NUDISCO_KEYWORDS,
    "numetal": NUMETAL_KEYWORDS,
    "mashup": MASHUP_KEYWORDS,
    "eighties": EIGHTIES_KEYWORDS,
    "nineties": NINETIES_KEYWORDS,
    "twothousands": TWOTHOUSANDS_KEYWORDS,
    "deep_melodic_house": DEEP_MELODIC_HOUSE_KEYWORDS,
    "afro_house": AFRO_HOUSE_KEYWORDS,
    "hard_dance": HARD_DANCE_KEYWORDS,
    "drill": DRILL_KEYWORDS,
    "balkan_gypsy": BALKAN_GYPSY_KEYWORDS,
    "world_ethnic": WORLD_ETHNIC_KEYWORDS,
    "ecstatic_ceremony": ECSTATIC_CEREMONY_KEYWORDS,
    "chill_downtempo": CHILL_DOWNTEMPO_KEYWORDS,
    "indie_altpop": INDIE_ALTPOP_KEYWORDS,
    "oldies_motown": OLDIES_MOTOWN_KEYWORDS,
    "rnb_soul_modern": RNB_SOUL_MODERN_KEYWORDS,
    "wedding_ceremony": WEDDING_CEREMONY_KEYWORDS,
}


# ---------------------------------------------------------------------------
# Disney and screen music, v20.
#
# Three separate crates on purpose. At a party the original is nostalgia and a
# singalong, the remix is a floor weapon, and the acoustic cover is a slow
# moment or a first dance. Filing all three together makes all three useless.
# ---------------------------------------------------------------------------

_DISNEY_TITLES = [
    "let it go", "into the unknown", "show yourself", "frozen heart",
    "a whole new world", "friend like me", "prince ali", "arabian nights",
    "under the sea", "part of your world", "kiss the girl", "poor unfortunate",
    "circle of life", "hakuna matata", "can you feel the love tonight",
    "be prepared", "i just can't wait to be king",
    "beauty and the beast", "be our guest", "gaston", "tale as old as time",
    "you'll be in my heart", "son of man", "trashin the camp",
    "colors of the wind", "just around the riverbend",
    "reflection", "i'll make a man out of you", "honor to us all",
    "how far i'll go", "you're welcome", "shiny", "we know the way",
    "remember me", "un poco loco", "the world es mi familia",
    "surface pressure", "we don't talk about bruno", "what else can i do",
    "when will my life begin", "i see the light", "mother knows best",
    "for the first time in forever", "do you want to build a snowman",
    "bibbidi bobbidi", "a dream is a wish", "so this is love",
    "when you wish upon a star", "heigh ho", "someday my prince will come",
    "supercalifragilistic", "chim chim cher", "feed the birds",
    "bare necessities", "i wanna be like you", "colonel hathi",
    "zip a dee doo dah", "the second star", "you can fly",
    "spoonful of sugar", "cruella de vil", "everybody wants to be a cat",
    "he's a tramp", "bella notte", "once upon a dream",
    "go the distance", "zero to hero", "i won't say i'm in love",
    "topsy turvy", "out there", "god help the outcasts",
    "strangers like me", "two worlds", "dig a little deeper",
    "almost there", "friends on the other side", "down in new orleans",
    "married life", "life is a highway", "you've got a friend in me",
    "toy story", "if i didn't have you", "immortals big hero",
    "try everything", "lava short", "the incredits",
    "encanto", "moana", "coco", "zootopia", "tangled", "brave",
]

_DISNEY_STUDIOS = [
    "disney", "walt disney", "pixar", "disney pixar", "dreamworks",
    "disney channel", "disneyland", "mickey mouse", "high school musical",
    "descendants", "camp rock", "hannah montana",
    "alan menken", "howard ashman", "sherman brothers",
    "kristen anderson-lopez", "robert lopez", "randy newman",
    "lin-manuel miranda disney", "idina menzel", "auli'i cravalho",
    "jodi benson", "paige o'hara", "lea salonga", "brad kane",
    "phil collins tarzan", "elton john lion king", "tim rice disney",
]

_REMIX_SIGNALS = [
    "remix", "bootleg", "flip", "edit)", "vip mix", "rework", "refix",
    "bounce", "hardstyle", "dnb", "drum & bass", "techno", "house mix",
    "festival mix", "trap mix", "club mix", "banger", "mashup",
]

_COVER_SIGNALS = [
    "cover", "acoustic", "piano", "lullaby", "instrumental", "music box",
    "string quartet", "violin", "harp", "a cappella", "acapella cover",
    "vitamin string", "rockabye baby", "jazz cover", "bossa cover",
    "slow version", "unplugged", "orchestral", "choir",
]

DISNEY_KEYWORDS = _DISNEY_TITLES + _DISNEY_STUDIOS

DISNEY_REMIX_KEYWORDS = [
    f"{t} ({r}" for t in ("let it go", "hakuna matata", "under the sea",
                          "a whole new world", "circle of life", "friend like me")
    for r in ("remix", "bootleg", "flip", "edit")
] + [
    "disney remix", "disney bootleg", "disney edit", "disney flip",
    "disney bounce", "disney hardstyle", "disney trap", "disney dnb",
    "disney mashup", "disney rave", "disney festival", "disney banger",
    "pixar remix", "frozen remix", "moana remix", "encanto remix",
    "lion king remix", "aladdin remix", "mulan remix", "tangled remix",
]

DISNEY_COVER_KEYWORDS = [
    "disney cover", "disney acoustic", "disney piano", "disney lullaby",
    "disney instrumental", "disney music box", "disney violin",
    "disney string quartet", "disney jazz", "disney a cappella",
    "rockabye baby", "vitamin string quartet disney",
    "lullaby renditions of disney", "disney orchestral",
]

SOUNDTRACK_KEYWORDS = [
    "original soundtrack", "motion picture soundtrack", "ost ",
    "film score", "movie theme", "main theme", "opening theme",
    "end credits", "hans zimmer", "john williams", "ennio morricone",
    "danny elfman", "howard shore", "ludwig goransson", "michael giacchino",
    "james horner", "thomas newman", "james newton howard", "ramin djawadi",
    "harry potter", "star wars", "james bond", "mission impossible",
    "pirates of the caribbean", "lord of the rings", "game of thrones",
    "stranger things", "peaky blinders", "top gun", "rocky theme",
    "ghostbusters", "back to the future", "jurassic park", "indiana jones",
    "the greatest showman", "la la land", "mamma mia", "grease soundtrack",
    "dirty dancing soundtrack", "pulp fiction soundtrack", "trainspotting",
    "guardians of the galaxy awesome mix", "barbie the album",
]

# Registered here so the classifier picks them up with everything else.
OPENFORMAT_KEYWORDS["disney_remix"] = DISNEY_REMIX_KEYWORDS
OPENFORMAT_KEYWORDS["disney_covers"] = DISNEY_COVER_KEYWORDS
OPENFORMAT_KEYWORDS["disney"] = DISNEY_KEYWORDS
OPENFORMAT_KEYWORDS["soundtrack"] = SOUNDTRACK_KEYWORDS

DISNEY_REMIX_SIGNALS = _REMIX_SIGNALS
DISNEY_COVER_SIGNALS = _COVER_SIGNALS


# ---------------------------------------------------------------------------
# Artists pulled straight from a real DJ's INBOX, v20.
#
# A test scan of a working library put 66 percent of tracks in INBOX. Reading
# the artist tag instead of only the filename recovered a large share, but the
# rest were simply current artists no keyword list knew about. These are the
# names that were actually sitting unclassified, so they are not guesses.
# ---------------------------------------------------------------------------

UKG_BASS_2020S = [
    "sammy virji", "interplanetary criminal", "salute", "main phase",
    "hamdi", "bakey", "kettama", "skepsis", "conducta", "holy goof",
    "chris lorenzo", "tsuki", "y u qt", "mph ", "tisoki", "1991 dnb",
    "bou ", "hedex", "a.m.c", "turno", "kanine", "benny l", "sota ",
    "window kid", "flowdan", "badger", "notion", "hybrid minds",
    "koven", "culture shock", "dimension", "wilkinson", "sub focus",
    "camoufly", "svdko", "aloka", "higgo", "oppidan", "subjoi",
]

NU_JAZZ_BROKEN_BEAT = [
    "alfa mist", "surprise chef", "soda island", "cameo blush",
    "richard spaven", "sandunes", "athletic progression", "move 78",
    "cody currie", "retromigration", "str4ta", "lance ferguson",
    "yussef dayes", "ezra collective", "kokoroko", "nubya garcia",
    "tom misch", "mansur brown", "blue lab beats", "emma-jean thackray",
    "children of zeus", "sault ", "jordan rakei", "hiatus kaiyote",
]

MODERN_ELECTRONIC_MISC = [
    "biianco", "xique-xique", "herzeloyde", "flavien berger", "gemi ",
    "hans glader", "nikita, the wicked", "drinks on me", "iomigrant",
    "anomalie", "bad snacks", "prem joshua", "manish vyas", "aukai",
    "k+lab", "nicolas duque", "4b ", "viperactive", "kon ", "fiorious",
    "saturday love", "chediak", "crosstalk", "janoska ensemble",
]

OPENFORMAT_KEYWORDS["bass_dnb_garage"] = (
    OPENFORMAT_KEYWORDS.get("bass_dnb_garage", []) + UKG_BASS_2020S)
OPENFORMAT_KEYWORDS["chill_downtempo"] = (
    OPENFORMAT_KEYWORDS.get("chill_downtempo", []) + NU_JAZZ_BROKEN_BEAT)
OPENFORMAT_KEYWORDS["electronic"] = (
    OPENFORMAT_KEYWORDS.get("electronic", []) + MODERN_ELECTRONIC_MISC)


# ---------------------------------------------------------------------------
# v20 split lists.
#
# A DJ reaching for a record mid-set thinks in one word: "garage", "disco",
# "techno". Compound folders like "Bass DnB & Garage" force a second decision
# at the worst possible moment, so every merged crate was split and the
# keywords routed to the sharper side.
# ---------------------------------------------------------------------------

TECH_HOUSE_KEYWORDS = [
    "tech house", "fisher", "chris lake", "solardo", "patrick topping",
    "hot since 82", "green velvet", "cloonee", "dom dolla", "john summit",
    "james hype", "michael bibi", "sosa uk", "wade ", "latmun", "mason maynard",
    "eli brown", "biscits", "kevin knapp", "danny howard", "billy gillies",
]
TECHNO_ONLY_KEYWORDS = [
    "techno", "charlotte de witte", "amelie lens", "adam beyer", "carl cox",
    "richie hawtin", "boris brejcha", "drumcode", "nina kraviz", "i hate models",
    "reinier zonneveld", "899", "kobosil", "sara landry", "hard techno",
    "minimal techno", "melodic techno", "industrial techno", "peak time techno",
]
DISCO_ONLY_KEYWORDS = [
    "disco", "bee gees", "chic ", "nile rodgers", "donna summer",
    "earth wind & fire", "kool & the gang", "sister sledge", "the trammps",
    "gloria gaynor", "village people", "abba", "boney m", "kc and the sunshine",
    "diana ross", "the jacksons", "shalamar", "cerrone", "giorgio moroder",
    "italo disco", "discotheque", "studio 54", "saturday night fever",
]
NUDISCO_KEYWORDS = [
    "nu disco", "nu-disco", "purple disco machine", "dimitri from paris",
    "todd terje", "breakbot", "roisin murphy", "l'imperatrice", "parcels",
    "folamour", "yuksek", "kraak & smaak", "the reflex", "dr packer",
    "michael gray", "aeroplane", "escort ", "jungle band", "french house",
    "filter house", "daft punk", "justice ", "cassius ", "modjo", "stardust",
]
PSYTRANCE_KEYWORDS = [
    "psytrance", "psy trance", "goa trance", "vini vici", "astrix",
    "infected mushroom", "ace ventura", "captain hook", "berg ", "liquid soul",
    "ritmo ", "blastoyz", "hilight tribe", "shpongle", "full on", "hi-tech psy",
    "forest psy", "progressive psy", "psychedelic trance",
]
TRANCE_ONLY_KEYWORDS = [
    "trance", "armin van buuren", "above & beyond", "paul van dyk",
    "ferry corsten", "gareth emery", "cosmic gate", "aly & fila", "anjunabeats",
    "a state of trance", "uplifting trance", "vocal trance", "andrew rayel",
]
DNB_ONLY_KEYWORDS = [
    "drum & bass", "drum and bass", "dnb", "d&b", "liquid dnb", "neurofunk",
    "netsky", "sub focus", "wilkinson", "pendulum", "chase & status", "andy c",
    "hybrid minds", "dimension", "culture shock", "koven", "metrik", "rudimental",
    "maduk", "logistics", "high contrast", "camo & krooked", "fred v", "grafix",
    "london elektricity", "matrix & futurebound", "kings of the rollers",
    "bou ", "hedex", "a.m.c", "turno", "macky gee", "benny l", "mefjus",
    "noisia", "black sun empire", "delta heavy", "dc breaks", "1991 dnb",
]
GARAGE_KEYWORDS = [
    "uk garage", "ukg", "2 step", "2-step", "speed garage", "bassline",
    "sammy virji", "interplanetary criminal", "main phase", "salute ",
    "conducta", "bakey", "skepsis", "holy goof", "chris lorenzo", "kettama",
    "todd edwards", "mj cole", "artful dodger", "wookie ", "burial ",
    "sherelle", "window kid", "notion ", "badger ", "y u qt", "tsuki ",
]
TWERK_ONLY_KEYWORDS = [
    "twerk", "jersey club", "juke ", "booty bass", "percolat", "shake dat",
    "donk ", "baltimore club", "ghetto tech",
]
TRAP_ONLY_KEYWORDS = [
    "trap ", "migos", "travis scott", "gucci mane", "21 savage", "lil uzi",
    "playboi carti", "metro boomin", "waka flocka", "rae sremmurd", "baauer",
    "rl grime", "flosstradamus", "carnage ", "yellow claw", "ape drums",
]
REGGAE_ONLY_KEYWORDS = [
    "reggae", "bob marley", "peter tosh", "jimmy cliff", "toots and the maytals",
    "burning spear", "gregory isaacs", "dennis brown", "steel pulse",
    "roots reggae", "lovers rock", "dub plate", "rocksteady", "ska ",
    "protoje", "chronixx", "damian marley", "ziggy marley",
]
DANCEHALL_KEYWORDS = [
    "dancehall", "sean paul", "shaggy", "vybz kartel", "popcaan", "spice ",
    "beenie man", "bounty killer", "elephant man", "konshens", "shenseea",
    "skillibeng", "masicka", "gyptian", "mr vegas", "busy signal", "alkaline",
]
REGGAETON_ONLY_KEYWORDS = [
    "reggaeton", "daddy yankee", "j balvin", "bad bunny", "don omar", "ozuna",
    "maluma", "karol g", "wisin", "yandel", "nicky jam", "farruko", "tego calderon",
    "rauw alejandro", "feid ", "myke towers", "arcangel", "de la ghetto",
    "anuel aa", "becky g", "natti natasha", "sech ", "dembow",
]
MOOMBAHTON_KEYWORDS = [
    "moombahton", "dave nada", "munchi ", "moombahcore", "moombah",
]
PUNK_ONLY_KEYWORDS = [
    "blink-182", "green day", "the offspring", "sum 41", "ramones",
    "sex pistols", "the clash", "bad religion", "nofx", "rancid", "misfits",
    "anti-flag", "pennywise", "descendents", "social distortion", "dead kennedys",
    "punk rock", "pop punk", "hardcore punk", "skate punk",
]
FUNK_ONLY_KEYWORDS = [
    "funk", "james brown", "parliament", "funkadelic", "bootsy collins",
    "the meters", "tower of power", "average white band", "cameo ",
    "rick james", "zapp ", "roger troutman", "the gap band", "ohio players",
    "vulfpeck", "cory wong", "jamiroquai", "incognito ", "brand new heavies",
]
SOUL_ONLY_KEYWORDS = [
    "soul", "aretha franklin", "otis redding", "sam cooke", "al green",
    "bill withers", "curtis mayfield", "donny hathaway", "roberta flack",
    "isaac hayes", "gladys knight", "the isley brothers", "teddy pendergrass",
    "northern soul", "southern soul", "deep soul",
]
MOTOWN_KEYWORDS = [
    "motown", "the supremes", "marvin gaye", "the temptations", "four tops",
    "smokey robinson", "the miracles", "martha and the vandellas",
    "jackson 5", "the jackson five", "mary wells", "edwin starr",
    "junior walker", "the marvelettes", "tammi terrell",
]
JAZZ_KEYWORDS = [
    "jazz", "miles davis", "john coltrane", "duke ellington", "louis armstrong",
    "ella fitzgerald", "billie holiday", "nina simone", "dave brubeck",
    "thelonious monk", "chet baker", "stan getz", "herbie hancock",
    "bossa nova", "big band", "swing ", "bebop", "nu jazz", "jazz funk",
    "alfa mist", "yussef dayes", "ezra collective", "kamasi washington",
]
SLOW_JAMS_KEYWORDS = [
    "slow jam", "quiet storm", "baby making", "bedroom playlist",
    "boyz ii men", "jodeci", "keith sweat", "silk ", "112 ", "next ",
    "dru hill", "joe ", "case ", "tank ", "avant ", "ginuwine",
]

OPENFORMAT_KEYWORDS.update({
    "tech_house": TECH_HOUSE_KEYWORDS,
    "techno": TECHNO_ONLY_KEYWORDS,
    "disco": DISCO_ONLY_KEYWORDS,
    "nudisco": NUDISCO_KEYWORDS,
    "trance": TRANCE_ONLY_KEYWORDS,
    "psytrance": PSYTRANCE_KEYWORDS,
    "dnb": DNB_ONLY_KEYWORDS,
    "garage": GARAGE_KEYWORDS,
    "trap": TRAP_ONLY_KEYWORDS,
    "twerk": TWERK_ONLY_KEYWORDS,
    "reggae": REGGAE_ONLY_KEYWORDS,
    "dancehall": DANCEHALL_KEYWORDS,
    "reggaeton": REGGAETON_ONLY_KEYWORDS,
    "moombahton": MOOMBAHTON_KEYWORDS,
    "baile_funk": OPENFORMAT_KEYWORDS.get("global_bass", []),
    "balkan": OPENFORMAT_KEYWORDS.get("balkan_gypsy", []),
    "rnb": OPENFORMAT_KEYWORDS.get("rnb_soul_modern", []),
    "punk": PUNK_ONLY_KEYWORDS,
    "funk": FUNK_ONLY_KEYWORDS,
    "soul": SOUL_ONLY_KEYWORDS,
    "motown": MOTOWN_KEYWORDS,
    "jazz": JAZZ_KEYWORDS,
    "slow": SLOW_JAMS_KEYWORDS,
})
