# engine/keywords.py
"""All genre keyword lists. Pure data — no logic.

Extracted from v18 (sort_main_crate.py) and reorganized for v19's genre structure.
Remapping rules applied:
  - v18 "techno"  → v19 "electronic"
  - v18 "trance"  → v19 "electronic"
  - v18 "bass"    → v19 "bass_dnb_garage" (+ uk garage, 2-step, bassline, 2step, ukg added)
  - v18 "world"   → v19 "electronic" for ambient/downtempo; "reggae_dancehall" for reggae/ska/dub
  - v18 "afrobeats" amapiano-specific → v19 "amapiano"; rest stays in v19 "afrobeats"
  - v18 "remixes" → REMOVED (handled by mix_type tag in tagger)
  - v18 "classics" → v19 "funk_disco_soul" for soul/funk/disco roots; rest stays "electronic" or discarded
  - Locale genres (israeli, arabic, etc.) NOT here — they use character detection only
  - Classics NOT here — detected by year, not keywords
"""

TOOLS_KEYWORDS = [
    "drum sample", "drum kit", "drum loop", "sample pack",
    " fx_", "_fx_", "fx ", "sound effect", "transition",
    "white noise", "intro tool", "dj tool", "acapella",
    "a cappella", "stab ", "clap ", "kick ",
    "snare ", "hihat", "hi hat", "cymbal",
    "bass loop", "build up", "build-up", "drop tool",
    "scratch ", "crowd cheer", "crowd noise", "air horn",
    "countdown", "vinyl crackle", "record scratch",
    "percussion sample", "instrument loop",
    # Ethnic/world percussion & drum machine sample files
    "dhol ", "dholak", "djembe ", "kenkeni", "krin ",
    "tambora ", "linndrum", "linn drum", "cowbell ",
    "shaker ", "conga ", "bongo ", "clave ", "timbale",
    "guiro", "agogo", "cabasa", "maracas",
    "perc abacaxi", "perc loop", "perc hit",
    "low conga", "hi conga", "lo conga",
    "vox miami",
    " 7t8", " 727 ", " 808 ", " 909 ", " 707 ",
    " dmx ",
    "hihat", "clhat", "closedhat", "openhat", "pedhat",
    "hitom", "midtom", "lotom", "lowtom",
    "rimshot", "rim shot", "tamb loop",
    "openhh",
    "closedhh",
    "kryptogram",
    "traktorset",
    "pfc midburn",
]

HOUSE_KEYWORDS = [
    # ─ Organic / indie house ─
    "maestracci",
    "earth n days",
    "saxity",
    "blackboxx",
    "timeless glow",
    "bakermat",
    "secondcity",
    "block & crown", "block and crown",
    "modjo",
    "madison avenue",
    "funkanomics",
    "galantis",
    "shiba san",
    # ─ Big EDM / progressive house ─
    "calvin harris", "david guetta", "tiësto", "tiesto",
    "avicii", "martin garrix", "hardwell", "afrojack",
    "swedish house mafia", "swedish house",
    "eric prydz", "fedde le grand", "nicky romero",
    "armin van buuren", "van buuren",
    "above & beyond", "above and beyond",
    "faithless", "fatboy slim",
    "basement jaxx", "groove armada",
    "bob sinclar", "bob sinclair",
    "dj snake", "dj khaled", "marshmello",
    "kygo ", "robin schulz",
    "alesso", "zedd ",
    "kshmr", "showtek", "bassjackers",
    "ummet ozcan", "w&w ",
    "blasterjaxx", "thomas gold", "chuckie",
    "laidback luke", "r3hab", "tom staar",
    "nervo", "yellow claw",
    "sigma ",
    # ─ Deep / tropical house ─
    "duke dumont", "disclosure",
    "route 94", "mk ",
    "gorgon city", "sam feldt",
    "lost frequencies", "kungs ",
    "ofenbach", "regard ",
    "meduza", "sofi tukker",
    "purple disco machine",
    "claptone", "tensnake",
    "breakbot", "todd terje",
    "bicep ", "jon hopkins",
    "boiler room",
    # ─ UK garage / 2-step ─
    "craig david", "mj cole",
    "so solid crew",
    "artful dodger", "shanks & bigfoot",
    "oxide & neutrino",
    # ─ Classic/commercial house artists ─
    "crystal waters",
    "milk & sugar", "milk and sugar",
    "dr. alban", "dr alban",
    "robin s",
    "erick morillo", "morillo",
    "hedegaard",
    "coeo",
    "eva simons",
    "saison ",
    "deep matter",
    # ─ Classic house ─
    "frankie knuckles", "larry levan",
    "larry heard", "mr fingers", "todd terry",
    "kerri chandler", "dj harvey",
    "marshall jefferson", "junior jack",
    "louie vega", "david morales",
    "frankie going hollywood",
    # ─ Tech house ─
    "hot since 82", "marco carola",
    "jamie jones", "seth troxler",
    "green velvet", "detlef",
    "george fitzgerald", "richy ahmed",
    "hannah wants", "jack back",
    "dirtybird", "justin martin",
    "waFF", "miguel clarimond",
    # ─ Melodic house ─
    "anyma", "massano", "innellea",
    "tale of us", "afterlife",
    "modeplex", "amelie lens",
    # ─ Afro house ─
    "black coffee", "themba ",
    "enoo napa", "culoe de song",
    "christos fourkis",
    # ─ Crossover pop-house ─
    "ellie goulding", "john newman",
    "rudimental", "becky hill",
    "ella henderson", "jess glynne",
    "paloma faith", "charli xcx",
    "bebe rexha", "jasmine thompson",
    # ─ Commercial dance / eurodance ─
    "benny benassi", "scooter",
    "cascada", "alice dj", "alice deejay",
    "darude", "atb ",
    "ian van dahl", "lasgo",
    "djs from mars",
    "bob the builder",
    "vengaboys", "dj bobo",
    "2 unlimited", "haddaway",
    "snap ", "la bouche", "real mccoy",
    "corona ", "livin joy",
    "culture beat", "alexia",
    "technotronic", "twenty 4 seven",
    "lmfao", "redfoo",
    "will i am", "will.i.am",
    "taio cruz",
    # ─ Garage / bass house ─
    "skream", "benga ", "joy orbison",
    "bok bok", "alex schulmman",
    # ─ House artists (expanded) ─
    "armand van helden",
    "fisher ",
    "shapeshifters",
    "ultra nate", "ultra naté",
    "yolanda be cool",
    "defkline",
    "illyus & barrientos", "illyus and barrientos",
    "eli & fur", "eli and fur",
    "bedouin",
    "stephan bodzin",
    "ben böhmer", "ben bohmer",
    "&me ",
    "rampa ",
    "adam port",
    "keinemusik",
    "woo york",
    "patrice bäumel", "patrice baumel",
    "marino canal",
    "tinlicker",
    "pretty pink",
    "dj dep",
    "sam paganini",
    "huxley ",
    "eats everything",
    "cause & affect", "cause and affect",
    "bontan ",
    "ejeca ",
    "cinthie ",
    "dj steaw",
    "blondish",
    "nicone ",
    "chaim ",
    "dj hell",
    "miss kittin", "miss kittin & the hacker",
    "the hacker",
    "dan bell",
    "paul kalkbrenner",
    "charlotte de witte",
    "peggy gou",
    "honey dijon",
    "dj stingray",
    "moodymann",
    "theo parrish",
    "kyle hall",
    # ─ Record labels in filenames ─
    "defected", "toolroom", "spinnin",
    "ministry of sound", "monstercat",
    "cr2 records", "hed kandi",
    "nervous records", "glitterbox",
    "ultra records", "big beat",
    "positiva", "data records",
    "all around the world", "v recordings",
    # ─ Genre terms ─
    "house ", " house_", "deep house", "tech house",
    "progressive house", "electro house",
    "dance floor", "dancefloor", "club mix", "club edit",
    "extended mix", "radio edit", "original mix",
    "_extended_mix", "_original_mix", "_club_mix", "_radio_edit",
    "bootleg", "mashup", "mash-up", "mash up",
    "nu disco", "nudisco",
    "afrohouse", "afro house", "tropical house",
    "funky house", "soulful house",
    "jackin house", "tribal house",
    "uk garage", "future bass", "bass house",
    "dj set", "live set", "festival mix",
    "disco ", "funky ",
    "acid house", "chicago house", "french house", "dutch house",
    "latin house", "minimal house", "ghetto house", "vocal house",
    "diva house", "italo house", "bounce house", "swing house",
    "speed garage", "garage house",
    "eurodance", "euro dance", "italo dance", "hi-nrg", "hi nrg",
    "electroswing", "electro swing", "electro-swing",
    "dance pop", "dance-pop",
    "freestyle ", "freestyle house",
    "boogie ", "post-disco", "post disco",
    "hard dance", "bouncy techno",
    "deee-lite", "deee lite",
    "stardust ",
    "moloko",
    "lissat",
    "low steppa",
    "low_steppa",
    "freed from desire",
    "rui da silva",
    "david penn",
    "arthur baker",
    "victor simonelli",
    "john morales",
    "dj spen",
    "will clarke ",
    "michelle weeks",
    "djane housekat",
    "housekat",
    "agatino romero",
    "bruno martini",
    "breach ",
    "bodybangers",
    "chelina manuhutu",
    "chris lorenzo",
    "croatia squad",
    "combustibles",
    "criminal vibes",
    "dombresky",
    "funkatron",
    "gamper ",
    "krystal klear",
    "laserkraft",
    "lee foss",
    "lil' louis",
    "lil louis",
    "mobin master",
    "me & my toothbrush",
    "michael mind",
    "mike candys",
    "nari & milani",
    "cristian marchi",
    "never dull",
    "picard brothers",
    "san pacho",
    "toomanylefthands",
    "vato gonzalez",
    "jolyon petch",
    "masteria",
    "babert",
    "mell hall",
    "black loops",
    "youandewan",
    "fort romeau",
    "drinks on me",
    "david versace",
    "tenshu",
    "kdyn",
    "harrison bdp",
    "ootoro",
    "cortese",
    "argy ",
    "darius & finlay",
    "dj sammy",
    "french affair",
    "martin jensen",
    "remady",
    "lothief",
    "sam shure",
    "audiosonik",
    "début de soirée",
    "debut de soiree",
    "lika morgan",
    "franky wah",
    "john summit",
    "jean tonique",
    "braga circuit",
    "herr krank",
    "delroy edwards",
    "stazzia",
    "douvelle",
    "100% pure love",
    "the bomb ",
    "the business",
    "blackwater",
    "tapesh",
    "dayne s",
    "cid & joshwa",
    "cid and joshwa",
    "chagu",
    "henrik schwarz",
    "bassboy",
    "renart",
    "bryn christopher",
    "alors on danse",
    "drinkee",
    "ed marquis",
    "estoy feliz",
    "gta ",
    "feder ",
    "666 ",
    "guetta",
    "garrix",
    "peniston",
    "nombe",
    "prospa",
    "paul woolford",
    "oden ",
    "yves v",
    "you man",
    "reel2real",
    "ecuador",
    "carnaval de paris",
    "head & heart",
    "in and out of love",
    "lucas ",
    "coke & rum",
    "piano banana",
    "chris lake",
    "beat freak",
    "if it ain't love",
    "we wanna party",
    "don't wanna go home",
    "sweet lovin",
    "mufasa",
    "just kiddin",
    "in da getto",
    "praise you",
    "rhythm is a dancer",
    "kia love",
    "mallin",
    "vula",
    "ray chris",
    "baian",
    "gonna_get_you",
    "the sponges",
    "tuxedo",
    "titanium",
    "karen_harding",
    "alaia",
    "yowsah",
]

AMAPIANO_KEYWORDS = [
    # ─ Amapiano-specific artists ─
    "kabza de small",
    "dj maphorisa",
    "focalistic",
    "uncle waffles",
    "costa titch",
    "major league djz",
    "scorpion kings",
    "musa keys",
    "vigro deep",
    # ─ Genre terms ─
    "amapiano",
    "log drum",
    "piano kwaito",
    "gqom", "gqom ",
    "kwaito",
]

AFROBEATS_KEYWORDS = [
    # ─ Afrobeats / Afropop artists ─
    "wizkid",
    "burna boy",
    "davido",
    "tiwa savage",
    "yemi alade",
    "tems ",
    "ckay ",
    "fireboy dml",
    "rema ",
    "omah lay",
    "asake",
    "ayra starr",
    "joeboy",
    "patoranking",
    "tekno ",
    "mr eazi",
    "aya nakamura",
    "fela kuti", "fela ",
    "lijadu sisters",
    "magic system",
    # ─ Dancehall / Soca ─
    "shabba ranks", "buju banton",
    "beenie man", "sean paul",
    "shaggy", "vybz kartel",
    "popcaan", "alkaline",
    "spice ",
    "machel montano",
    "bunji garlin",
    "bombo clat",
    # ─ Genre terms ─
    "afrobeats", "afropop", "afro-pop",
    "afrobeat", "afro-beat",
    "bongo flava",
    "highlife", "soukous", "makossa",
    "kuduro", "semba ",
    "coupe decale", "coupé-décalé",
    "dancehall",
    "soca ", "calypso",
]

REGGAE_DANCEHALL_KEYWORDS = [
    # ─ Reggae artists ─
    "bob marley", "marley",
    "peter tosh", "bunny wailer",
    "jimmy cliff", "toots",
    "burning spear", "culture ",
    "dawn penn",
    "the congos",
    "inner circle",
    "the slickers",
    # ─ Genre terms ─
    "reggae", "roots reggae", "dub ",
    "ska ", "rocksteady", "lovers rock",
    "ragga ", "raggamuffin",
    "mento ",
    "bashment",
    "jungle ",
]

HIPHOP_KEYWORDS = [
    # ─ Added from tracklist analysis ─
    "eminem", "m.i.a.", "macklemore", "ryan lewis",
    "lizzo",
    # ─ Old school / Golden Age ─
    "run dmc", "run-dmc", "ll cool j",
    "public enemy", "nwa ", "n.w.a", "ice cube", "ice-t", "ice t",
    "beastie boys", "beastie",
    "tribe called quest", "a tribe called",
    "wu-tang", "wu tang", "method man", "raekwon", "ghostface",
    "ol dirty bastard", "odb ", "gza ", "rza ", "inspectah",
    "big l", "big pun", "big l ",
    "kool g rap", "kool moe dee",
    "slick rick", "mc lyte",
    # ─ 90s ─
    "nas ", "biggie", "notorious b.i.g", "notorious big",
    "2pac", "tupac", "snoop dogg", "snoop dog",
    "dr dre", "dr. dre", "death row",
    "mc hammer", "vanilla ice",
    "dmx ", "ja rule", "eve ", "ludacris",
    "nelly ", "outkast", "andre 3000", "big boi",
    "jay-z", "jay z",
    # ─ 2000s ─
    "kanye", "kanye west",
    "t.i.", " ti_", "young jeezy", "jeezy",
    "lil jon", "t-pain", "t pain",
    "flo rida", "akon ",
    "ne-yo", "ne yo", "chris brown",
    "soulja boy", "lil wayne", "weezy",
    "rick ross", "gucci mane", "young joc",
    "bow wow", "jermaine dupri", "chingy",
    "petey pablo", "david banner",
    "lupe fiasco", "common ", "mos def", "talib kweli",
    "the game ", "50 cent", "g-unit",
    "lloyd banks", "tony yayo",
    # ─ 2010s ─
    "drake", "nicki minaj", "wiz khalifa",
    "kendrick lamar", "kendrick",
    "j cole", "j. cole", "j.cole", "big k.r.i.t",
    "mac miller", "kid cudi", "cudi",
    "childish gambino", "donald glover",
    "tyler the creator", "tyler, the creator",
    "frank ocean", "the weeknd", "weeknd", "abel tesfaye",
    "meek mill", "big sean", "2 chainz", "2chainz",
    "chance the rapper", "vic mensa",
    "fetty wap", "rae sremmurd", "swae lee",
    "lil uzi", "future ", "young thug",
    "migos", "offset ", "quavo", "takeoff",
    "21 savage", "travis scott",
    "post malone", "logic ",
    "a$ap", "asap rocky", "asap mob",
    "missy elliott", "timbaland",
    "swizz beatz", "pharrell", "n.e.r.d",
    "action bronson", "schoolboy q",
    "vince staples", "earl sweatshirt",
    "joey bada$$", "joey badass",
    # ─ Missing hip-hop / R&B artists ─
    "heavy d", "heavy d and the boyz", "heavy d & the boyz",
    "will smith ",
    "lil dicky",
    "tego calderon", "tego calderón",
    "felt ",
    "serpentwithfeet",
    "lady wray",
    "dcappella",
    # ─ 2020s ─
    "polo g", "pop smoke", "lil baby",
    "dababy", "da baby", "nba youngboy",
    "jack harlow", "rod wave",
    "moneybagg yo", "lil durk", "king von",
    "doja cat", "saweetie", "megan thee stallion",
    "city girls", "young m.a",
    "gunna", "lil tecca", "lil mosey",
    "pooh shiesty", "42 dugg",
    "roddy ricch", "blueface", "shordie shordie",
    "lil nas x",
    # ─ R&B ─
    "usher", "alicia keys", "rihanna",
    "beyonce", "beyoncé",
    "mary j blige", "mary j. blige",
    "r kelly", "trey songz", "august alsina",
    "tank ", "miguel ",
    "jhene aiko", "jhene", "jhené aiko", "jhené", "h.e.r.",
    "summer walker", "sza ",
    "khalid", "daniel caesar",
    "bryson tiller", "partynextdoor", "pnd ",
    "6lack", "giveon", "brent faiyaz",
    "teyana taylor", "kehlani",
    "tinashe", "elle varner",
    "toni braxton", "brandy ", "monica ",
    "destiny's child", "destinys child",
    "tlc ", "en vogue", "salt-n-pepa", "salt n pepa",
    "erykah badu", "lauryn hill", "d'angelo", "dangelo",
    "jill scott", "india arie",
    "musiq soulchild", "anthony hamilton",
    # ─ UK grime / drill ─
    "stormzy", "skepta", "giggs ",
    "dave ", "slowthai", "headie one",
    "central cee", "digga d", "aitch ",
    "tion wayne", "russ millions",
    "nines", "ghetts", "wretch 32",
    "chip ", "dizzee rascal", "tinchy stryder",
    "tinie tempah", "wiley", "jme ",
    # ─ Hip-hop/R&B artists ─
    "naughty by nature",
    "fabolous",
    "wyclef jean",
    "geto boys", "scarface",
    "cam'ron", "killa cam",
    "biz markie",
    "sir mix-a-lot",
    "d12 ",
    "fat joe",
    "desiigner",
    "foxy brown",
    "ginuwine",
    "ying yang twins",
    "pras ",
    "ptaf ",
    "juvenile ",
    "silkk the shocker",
    "mystikal",
    "big tymers",
    "mack 10",
    "twista ",
    "bone thugs",
    "do or die",
    "spice 1",
    "mc ren",
    "above the law",
    "king tee",
    "compton's most wanted",
    "bad meets evil",
    "royce da 5",
    "yelawolf",
    "rittz ",
    "jarren benton",
    "hopsin",
    "futuristic",
    "machine gun kelly", "mgk ",
    "joyner lucas",
    "token ",
    "tom macdonald", "tom mcdonald",
    "lil pump",
    "smokepurpp",
    "zillakami",
    "city morgue",
    "flatbush zombies",
    "denzel curry",
    "rico nasty",
    "little simz",
    "lady leshurr",
    "shystie",
    "lady sovereign",
    # ─ Genre terms ─
    "hip hop", "hip-hop", "hiphop",
    "r&b", "rnb", "rap ",
    "trap ", "gangsta", "boom bap", "freestyle rap",
    "g-funk", "chopped", "slowed", "screwed",
    "cypher", "diss track", "mixtape",
    "grime", "uk drill", "afroswing",
    "afrobeats dj", "melodic rap",
    "dirty south", "crunk ", "hyphy ",
    "conscious hip hop", "jazz rap", "lo-fi hip hop",
    "instrumental hip hop", "turntablism",
    "horrorcore", "nerdcore",
    "new jack swing", "quiet storm",
    "neo-soul", "neo soul", "motown",
    "doo wop", "doo-wop", "doowop",
    "funk ", "soul ", "northern soul",
    "southern soul", "psychedelic soul",
    "contemporary r&b",
    "drill ", "chicago drill",
    "phonk ", "memphis rap",
    "cloud rap", "emo rap",
    "cardi b",
    "mobb deep",
    "young money",
    "sage the gemini",
    "kent jones",
    "nardo wick",
    "drapht",
    "hilltop hoods",
    "kota the friend",
    "erica banks",
    "azealia banks",
    "stefflon don",
    "yung gravy",
    "cali swag district",
    "lil mama",
    "dej loaf",
    "die antwoord",
    "nate dogg",
    "alligatoah",
    "gin and juice",
    "jeshi",
    "the rza",
    "bodak yellow",
    "gravel pit",
    "jump around",
    "nappy roots",
    "khia ",
    "dj chose",
    "earthgang",
    "shnekel",
    "skero ",
    "die atzen",
    "frauenarzt",
    "manny marc",
    "sdp ",
    "opm ",
    "rollin'",
    "bitch better have my money",
    "1, 2 step",
    "candy shop",
    "e.i.",
    "g.o.m.d.",
    "get busy",
    "goosebumps",
    "i just had sex",
    "industry baby",
    "like a g6",
    "paper planes",
    "run the world",
    "nice for what",
    "wild thing",
    "half moghul",
    "freddy madball",
    "antwoord",
    "formation",
    "madcon",
    "stallion",
    "yung joc",
    "it's goin' down",
    "lotto boyzz",
    "mr eazi",
    "vamummtn",
    "sumit ",
    "fort knox five",
    "the way you move",
    "the sky's the limit",
    "7_11",
    "imma be",
    "get ugly",
    "tambourine",
    "hateu",
    "lite weight",
    "all the stars",
    "ms banks",
    "allan rayman",
    "kiss me more",
    "milkshake",
    "ring the alarm",
    "nails, hair",
    "level up",
    "lose control",
    "step up",
]

LATIN_KEYWORDS = [
    # ─ Latin artists ─
    "ivete sangalo",
    "rosalía", "rosalia ",
    "santana ",
    "los lobos",
    "becky g",
    "jowell y randy",
    "trinidad cardona",
    "bonde do rolê",
    "bonde do role",
    "porto seguro",
    "carrapicho",
    "jorge ben", "jorge ben jor",
    "tim maia",
    "caetano veloso",
    "gilberto gil",
    "gal costa",
    "seu jorge",
    "mc bin laden",
    "l7nnon",
    "matuê",
    "veigh ",
    "xande de pilares",
    "thiaguinho",
    "rodriguinho",
    "nego do borel",
    # ─ Reggaeton ─
    "j balvin", "bad bunny", "daddy yankee", "shakira", "maluma",
    "ozuna", "anuel aa", "karol g", "nicky jam",
    "wisin", "yandel", "don omar",
    "rauw alejandro", "myke towers", "farruko",
    "sech", "jhay cortez", "justin quiles",
    "lunay", "lenny tavarez", "dalex",
    "quevedo", "paulo londra", "bizarrap",
    "duki", "peso pluma", "natanael cano",
    "christian nodal", "ivan cornejo",
    "grupo firme", "banda ms",
    "jhayco", "mora ",
    # ─ Latin pop ─
    "marc anthony", "jennifer lopez", "j.lo",
    "pitbull", "ricky martin", "enrique iglesias", "luis fonsi",
    "alejandro sanz", "juanes", "gloria estefan", "selena",
    "celia cruz", "hector lavoe", "willie colon",
    "olga tanon", "victor manuel", "pablo alboran",
    "alejandro fernandez", "carlos vives",
    "ana gabriel", "lupillo rivera",
    "pedro infante", "vicente fernandez",
    # ─ Brazilian ─
    "anitta", "alok ", "dennis dj",
    "mc kevinho", "mc pedrinho",
    "mc livinho", "mc lan",
    "funk carioca", "funk brasileiro",
    # ─ Global reggaeton / collab ─
    "despacito", "con calma", "danza kuduro",
    "macarena", "bailando", "la gozadera",
    "gasolina", "loca", "papi",
    # ─ Genre terms ─
    "reggaeton", "salsa", "bachata", "cumbia", "merengue",
    "latin pop", "urbano", "perreo", "dembow",
    "samba ", "bossa nova", "forró", "axé",
    "champeta", "vallenato", "mariachi",
    "latin jazz", "latin house",
    "moombahton", "latin trap",
    "corrido", "banda ", "norteño",
    "bolero ", "mambo ", "son cubano", "timba ",
    "ranchera", "tejano", "chicha",
    "flamenco", "nuevo flamenco", "rumba ",
    "tango ", "milonga ",
    "pagode", "sertanejo", "tecnobrega", "brega ",
    "baile funk",
    "lambada", "zouk ", "kizomba",
    "punta ", "soca ", "calypso",
    "latin rock", "rock en español", "rock latino",
    "reggaeton y hip-hop", "trap latino",
    "carlos gardel",
    "bomba estéreo", "bomba estereo",
    "mercedes sosa",
    "joan manuel serrat",
    "alvaro soler",
    "chambao",
    "los bravos",
    "proyecto uno",
    "naâman", "naaman",
    "king blvck",
    "rigoberta bandini",
    "nina sky",
    "kat deluna", "kat de luna",
    "los autenticos decadentes",
    "konshens",
    "rupee ",
    "lil bitts",
    "sergio mendes",
    "chingon",
    "delfina dib",
    "ludmilla",
    "berimbau",
    "calito",
    "carnavalera",
    "color esperanza",
    "muchachos",
    "trio vegabajeno",
    "rebelde way",
    "joaquín cornejo",
    "dj scuff",
    "nando boom",
    "dj bruno prado",
    "pa mayte",
    "veneno de serpiente",
    "mas maiz",
    "chu chu ua",
    "scubba",
    "radio luna",
    "cuentame",
]

BASS_DNB_GARAGE_KEYWORDS = [
    # ─ Drum & Bass ─
    "goldie", "ltj bukem",
    "roni size", "bad boy bill",
    "sub focus", "chase & status", "chase and status",
    "andy c", "high contrast",
    "pendulum", "total science", "calibre",
    "danny byrd", "shy fx",
    "congo natty", "dj marky",
    "logistics", "london elektricity",
    "hospital records",
    "wilkinson ",
    "mako ",
    "taiki nulight",
    "serial killaz",
    "frederic robinson",
    "clipz",
    "matrix & futurebound",
    # ─ Dubstep ─
    "benga ", "digital mystikz",
    "mala ", "coki ",
    "rusko", "caspa",
    "cookie monsta", "doctor p",
    "flux pavilion", "12th planet",
    "excision", "datsik",
    "skrillex", "borgore",
    "zomboy ",
    "subb theory",
    # ─ Bass / trap producers ─
    "nghtmre",
    "slander ",
    "troyboi ",
    "bassnectar",
    "rezz ",
    "hucci",
    "cirqular",
    "neuroplasm",
    "deekapz",
    "ahadadream",
    # ─ Genre terms ─
    "dubstep", "drum and bass", "drum & bass", "dnb",
    "drum n bass", "drum'n'bass", "drumstep", "darkstep",
    "liquid funk", "jump-up", "jump up", "drumfunk",
    "intelligent drum", "techstep",
    "neurofunk", "liquid dnb",
    "chillstep", "brostep", "riddim ",
    "bass music", "uk bass", "bassline",
    "breakcore", "speedcore", "terrorcore", "doomcore",
    "uk garage", "2-step", "2step", "ukg",
    "jungle",
]

POP_KEYWORDS = [
    # ─ Pop artists ─
    "prince ",
    "kylie minogue",
    "roxette",
    "omc ",
    "smash mouth",
    "lany ",
    "still woozy",
    "surfaces ",
    "electric guest",
    "inna ",
    "morgan wallen",
    "far east movement",
    "r.i.o.",
    "dj antoine",
    "eyja ",
    "her's ",
    "sports ",
    "feathers ",
    "kirk franklin",
    "dcappella ",
    "demi lovato",
    "gwen stefani",
    "p!nk",
    "ke$ha",
    "kesha",
    "jamiroquai",
    # ─ Mega-stars ─
    "taylor swift", "beyonce", "beyoncé",
    "lady gaga", "katy perry", "rihanna",
    "britney spears", "christina aguilera",
    "michael jackson", "madonna",
    "justin bieber", "ariana grande",
    "selena gomez", "miley cyrus",
    "dua lipa", "billie eilish",
    "harry styles", "one direction",
    "justin timberlake", "timberlake",
    # ─ Ed Sheeran / Sam Smith generation ─
    "ed sheeran", "sam smith", "adele ",
    "lewis capaldi", "niall horan",
    "shawn mendes", "camila cabello",
    "halsey", "lana del rey",
    "lorde", "troye sivan",
    "james arthur", "olly murs",
    "the script", "kodaline",
    "james bay", "tom odell",
    "charlie puth", "meghan trainor",
    "jason derulo", "sia ", "bebe rexha",
    # ─ 90s pop ─
    "nsync", "backstreet boys", "spice girls",
    "nelly furtado", "pink ",
    "fergie ", "black eyed peas",
    "maroon 5", "maroon5", "adam levine",
    "boy bands", "westlife", "blue ",
    "take that", "boyzone",
    "atomic kitten", "girls aloud",
    "sugababes", "liberty x",
    "pussycat dolls", "s club",
    "5ive", "ace of base", "abba ",
    "aqua ", "vengaboys", "a-ha ",
    "rob rob", "savage garden",
    "hanson ", "4 non blondes",
    "alanis morissette", "sheryl crow",
    "natalie imbruglia", "dido ",
    "norah jones", "katie melua",
    # ─ 2000s pop ─
    "kesha ", "katy perry",
    "kelly clarkson",
    "alicia keys",
    "fergie", "black eyed peas",
    "taio cruz", "jason derulo",
    "ne-yo",
    "pixie lott", "leona lewis",
    "n-dubz", "tinchy stryder",
    "chipmunk", "labrinth",
    "cher lloyd", "little mix",
    "one direction",
    "5 seconds of summer", "5sos",
    # ─ Current pop ─
    "olivia rodrigo", "sabrina carpenter",
    "gracie abrams", "conan gray",
    "rex orange county", "clairo",
    "girl in red", "phoebe bridgers",
    "beabadoobee", "powfu",
    "the chainsmokers", "chainsmokers",
    "zara larsson", "tove lo",
    "ellie goulding", "rita ora",
    "jess glynne", "ella henderson",
    "paloma faith", "jessie j",
    "carly rae jepsen", "neon trees",
    "walk the moon", "fun ",
    "owl city", "passion pit",
    "grouplove", "train ",
    "mike posner", "jason mraz",
    "john mayer", "james morrison",
    "james blunt", "daniel bedingfield",
    "daniel powter",
    # ─ Michael Bublé / adult contemporary ─
    "michael buble", "michael bublé",
    "jamie cullum", "diana krall",
    "josh groban", "gavin degraw",
    "john legend", "aloe blacc",
    "robin thicke",
    "sara bareilles", "ingrid michaelson",
    "colbie caillat", "jack johnson",
    "ben harper", "ben folds",
    "mat kearney",
    # ─ Imagine Dragons / modern pop rock ─
    "imagine dragons", "onerepublic", "one republic",
    "switchfoot", "lifehouse",
    "matchbox twenty",
    # ─ Eurodance / eurotrance crossover pop ─
    "haddaway", "snap ",
    "la bouche", "real mccoy", "corona ",
    "culture beat", "two unlimited",
    "mr president", "lou bega",
    "whigfield", "alexia",
    "twenty 4 seven",
    # ─ International pop ─
    "robyn", "loreen", "cornelia jakobs",
    "amy winehouse", "lily allen",
    "florence", "elbow ",
    "paolo nutini", "jake bugg",
    "james morrison", "scouting for girls",
    # ─ Pop genre terms ─
    "pop hit", "chart",
    "bubblegum", "teen pop",
    "electropop", "synthpop", "synth pop",
    "indie pop", "chamber pop",
    "adult contemporary",
    "idol ", "x factor",
    # ─ Pop artists (expanded) ─
    "gotye ",
    "george michael",
    "dnce ",
    "tones and i",
    "years & years", "years and years",
    "hailee steinfeld",
    "nico & vinz", "nico and vinz",
    "joji ",
    "jvke ",
    "jawsh 685",
    "josh golden",
    "griff ",
    "rina sawayama",
    "caroline polachek",
    "magdalena bay",
    "wet leg",
    "maisie peters",
    "raye ",
    "emma-louise",
    "dagny ",
    "astrid s",
    "aurora ",
    "sigrid",
    "icona pop",
    "annie lennox",
    "sinead o'connor", "sinead o connor",
    "dolores o'riordan",
    "k.d. lang", "kd lang",
    "melissa etheridge",
    "shania twain",
    "faith hill",
    "leann rimes",
    "jessica simpson",
    "hilary duff",
    "ashley tisdale",
    "vanessa hudgens",
    "jonas brothers",
    "mariah carey",
    "janet jackson",
    "bruno mars",
    "empire of the sun",
    "mgmt ",
    "blood orange",
    "chet faker",
    "nick murphy",
    "of monsters and men",
    "the neighbourhood", "nbhd ",
    "vance joy",
    "maggie rogers",
    "hozier",
    "jorja smith",
    "sigala ",
    "stephen sanchez",
    "nicky youre",
    "lake street dive",
    "todrick hall",
    "weyes blood",
    "kacey musgraves",
    "solange ",
    "cautious clay",
    "greatest showman",
    "banks - ",
    "whigfeild",
    "d4vd ",
    "ciara ",
    "fifth harmony",
    "jennifer paige",
    "nine days",
    "tal bachman",
    "ylvis",
    "t.a.t.u.", "tatu ",
    "michael kiwanuka",
    "mahalia ",
    "sault ",
    "devendra banhart",
    "the wanted",
    "willow smith",
    "ruth b.",
    "the marias", "the marías",
    "timeflies",
    "the sundays",
    "rascal flatts",
    "the band perry",
    "jesse mccartney",
    "lunchmoney lewis",
    "paula cole",
    "nicole scherzinger",
    "kelis ",
    "bran van 3000",
    "midlake",
    "kim petras",
    "ava max",
    "andra day",
    "shivaree",
    "dean and britta",
    "david gray",
    "grouper ",
    "mapei ",
    "broods ",
    "petite_meller",
    "petite meller",
    "aj mitchell",
    "24k magic",
    "unrest ",
    "april march",
    "ashnikko",
    "caroline rose",
    "the 6ths",
    "lewis ofman",
    "jp saxe",
    "noah cyrus",
    "gavin james",
    "neon jungle",
    "morly",
    "b*witched", "b witched",
    "banes world",
    "dennis lloyd",
    "b* witched",
    "idina menzel",
    "paenda",
    "sigala",
    "tessa rose jackson",
    "sure sure",
    "the wind and the wave",
    "thirdstory",
    "wild child ",
    "i gotta feeling",
    "geri halliwell",
    "dan balan",
    "gilbert montagne",
    "kimberose",
    "chesney hawkes",
    "leslie grace",
    "ariana and the rose",
    "möwe",
    "mowe ",
    "us the duo",
    "andreas bourani",
    "andrew belle",
    "agadou",
    "eryn allen kane",
    "nick mulvey",
    "just dance",
    "make me feel",
    "good as hell",
    "hold on, we're going home",
    "shape of you",
    "somebody that i used to know",
    "jonathan groff",
    "supercut",
    "the louvre",
    "temperature",
    "sheeran",
    "gambino",
    "iglesias",
    "derulo",
    "monae",
    "magnifico",
    "christoff",
    "wendler",
    "nadro",
    "malcolm mclaren",
    "lion king",
    "we saw lions",
    "coca-cola anthem",
    "colors ",
    "you'll be back",
    "i know him",
    "let it go",
    "leisure ",
    "koosen",
    "madison ryann",
    "acid dreams",
    "katerine",
    "healy",
    "kai straw",
    "one and only",
    "jason weaver",
    "boy - railway",
    # ─ Pop subgenres ─
    "bubblegum pop", "teen pop", "chamber pop",
    "indie pop", "indie-pop", "jangle pop",
    "electropop", "electro pop", "electro-pop",
    "bedroom pop", "hyperpop", "hyper pop",
    "k-pop", "kpop", "j-pop", "jpop", "c-pop", "cpop",
    "europop", "euro pop", "schlager",
    "power pop", "sunshine pop",
    "new romantic", "new romanticism",
    "easy listening",
    "chanson", "french pop",
]

FUNK_DISCO_SOUL_KEYWORDS = [
    # ─ Funk legends ─
    "james brown",
    "parliament",
    "george clinton",
    "sly & the family stone", "sly and the family stone",
    "sly stone",
    "kool and the gang", "kool & the gang",
    "earth wind and fire", "earth wind & fire",
    "earth, wind",
    "chic ",
    "sister sledge",
    "donna summer",
    "the commodores", "commodores",
    "lionel richie",
    # ─ Soul ─
    "marvin gaye", "stevie wonder",
    "aretha franklin", "ray charles",
    "diana ross",
    "the temptations", "four tops",
    "supremes",
    "gladys knight",
    "otis redding", "sam cooke",
    "wilson pickett", "solomon burke",
    "al green", "bill withers",
    "erykah badu",
    "jill scott", "india arie",
    "musiq soulchild", "anthony hamilton",
    # ─ Disco ─
    "bee gees", "stayin alive",
    "boney m", "village people",
    "nile rodgers",
    "gloria gaynor",
    "jacksons", "jackson 5",
    "donna summer",
    # ─ R&B / Soul roots ─
    "bb king", "b.b. king",
    "muddy waters", "john lee hooker",
    "chuck berry", "little richard",
    "fats domino", "bo diddley",
    "isaac hayes",
    "bobby womack",
    "chaka khan",
    "minnie riperton",
    "shuggie otis",
    "roy ayers",
    "brothers johnson",
    "quincy jones",
    "booker t",
    # ─ Genre terms ─
    "funk", "soul", "disco",
    "r&b classics", "rhythm and blues",
    "groove", "motown classics",
    "philly soul", "deep funk",
    "afrofunk", "afro funk",
    "p-funk", "go-go",
    "neo soul",
]

ROCK_KEYWORDS = [
    # ─ Alternative / indie rock ─
    "belle and sebastian", "belle & sebastian",
    "the magnetic fields", "magnetic fields",
    "the chills",
    "surf curse",
    "r.e.m.",
    "gang of four",
    "no doubt",
    "morrissey",
    "dinosaur jr", "dinosaur jr.",
    "they might be giants",
    "elliott smith",
    "nine inch nails",
    "velvet underground", "the velvet underground",
    "the stooges", "iggy pop", "iggy & the stooges",
    "pavement ",
    "built to spill",
    "lemonheads", "the lemonheads",
    "indigo girls",
    "cat power",
    "foxygen",
    "the dandy warhols", "dandy warhols",
    "mild high club",
    "japanese breakfast",
    "allah-las",
    "the clean ",
    "the sonics",
    "the growlers",
    "powderfinger",
    "liquid liquid",
    "slapp happy",
    "ac_dc",
    "fuel ",
    "the 5.6.7.8", "5.6.7.8",
    "the centurians", "centurians",
    "the durutti column", "durutti column",
    "rmr ",
    # ─ Heavy / metal ─
    "metallica", "slipknot", "korn",
    "system of a down", "soad",
    "rage against the machine", "ratm",
    "linkin park", "limp bizkit",
    "red hot chili peppers", "rhcp",
    "black sabbath", "ozzy", "iron maiden", "judas priest",
    "megadeth", "anthrax", "sepultura",
    "pantera", "slayer", "testament",
    "machine head", "death angel",
    "down ", "corrosion of conformity",
    "soulfly",
    # ─ Classic rock ─
    "led zeppelin", "pink floyd", "deep purple",
    "ac dc", "ac/dc",
    "guns n roses", "guns n' roses",
    "queen ", "aerosmith",
    "the who", "rolling stones",
    "the doors", "doors ",
    "jimi hendrix", "janis joplin",
    "creedence clearwater", "ccr ",
    "styx ", "foreigner", "boston ",
    "bon jovi", "def leppard",
    "motley crue", "motley crüe",
    "whitesnake", "poison ",
    "thin lizzy", "rainbow",
    # ─ 90s / alternative / grunge ─
    "nirvana", "pearl jam", "soundgarden",
    "alice in chains", "audioslave",
    "foo fighters", "weezer",
    "the offspring", "offspring",
    "green day", "blink-182", "blink 182", "sum 41",
    "smashing pumpkins", "silverchair",
    "bush ", "collective soul",
    "matchbox twenty", "matchbox 20",
    "third eye blind", "live ",
    "stone temple pilots", "stp",
    "tool ", "a perfect circle",
    # ─ 2000s rock ─
    "coldplay", "muse ", "radiohead",
    "the killers", "killers",
    "30 seconds to mars", "thirty seconds",
    "fall out boy", "panic at the disco",
    "my chemical romance", "paramore",
    "evanescence", "within temptation",
    "nickelback", "creed ", "staind",
    "puddle of mudd", "trapt",
    "breaking benjamin", "three days grace",
    "seether", "papa roach", "disturbed",
    "hinder", "theory of a deadman",
    "depeche mode", "the cure", "the smiths",
    "u2 ", "oasis ", "blur ", "pulp ",
    # ─ Indie / modern rock ─
    "arctic monkeys", "arctic",
    "arcade fire", "the national",
    "vampire weekend", "the strokes",
    "interpol", "bloc party",
    "kaiser chiefs", "razorlight",
    "the libertines", "jack white",
    "the white stripes", "white stripes",
    "the black keys", "black keys",
    "mumford and sons", "mumford & sons",
    "the xx ",
    "alt-j", "alt j",
    "bastille",
    "elbow ", "snow patrol",
    "biffy clyro", "frank turner",
    # ─ Metallica song titles (album-rip files have no artist name) ─
    "enter sandman",
    "for whom the bell tolls",
    "the call of ktulu", "call of ktulu",
    "until it sleeps",
    "eye of the beholder",
    "dirty window",
    "of wolf and man",
    "hero of the day",
    "orion (instrumental)",
    "bad seed",
    # ─ Rock artists (expanded) ─
    "pixies",
    "the police", "police ",
    "deftones",
    "yeah yeah yeahs",
    "cage the elephant",
    "the cranberries", "cranberries",
    "the cardigans", "cardigans",
    "the hives", "hives ",
    "goo goo dolls",
    "avril lavigne",
    "drowning pool",
    "godsmack",
    "everclear",
    "haim ",
    "jet ",
    "the vines",
    "the coral",
    "graham coxon",
    "supergrass",
    "suede ",
    "elastica",
    "sleeper ",
    "echobelly",
    "powder",
    "the breeders", "breeders",
    "throwing muses",
    "guided by voices", "gbv ",
    "big star ",
    "the replacements",
    "husker du", "hüsker dü",
    "mission of burma",
    "television ",
    "wire ",
    "siouxsie",
    "bauhaus ",
    "the sisters of mercy",
    "christian death",
    "type o negative",
    "my dying bride",
    "anathema",
    "paradise lost",
    "lacuna coil",
    "nightwish",
    "epica ",
    "after forever",
    # ─ Genre terms ─
    "rock ", "metal ", "punk ",
    "grunge", "alternative", "indie rock",
    "hard rock", "heavy metal", "nu metal", "nu-metal",
    "post-rock", "prog rock", "progressive rock",
    "classic rock", "glam rock",
    "screamo", "post-hardcore", "metalcore",
    "emo ", "pop punk", "skate punk",
    "stoner rock", "stoner metal", "doom metal",
    "thrash metal", "death metal", "black metal",
    "power metal", "speed metal", "groove metal",
    "symphonic metal", "gothic metal", "folk metal",
    "viking metal", "pagan metal", "pirate metal",
    "sludge ", "djent ", "math rock", "math metal",
    "grindcore", "deathcore", "crossover thrash",
    "psychedelic rock", "acid rock", "space rock",
    "shoegaze", "dream pop", "noise rock",
    "surf rock", "garage rock", "brit pop", "britpop",
    "art rock", "art punk", "new wave",
    "post-punk", "post punk", "goth rock", "gothic rock",
    "rockabilly", "psychobilly",
    "southern rock", "blues rock", "blues-rock",
    "yacht rock", "soft rock", "arena rock",
    "afro punk", "afropunk",
    "indie ", "lo-fi rock",
    "talking heads",
    "tom tom club",
    "sonic youth",
    "stereolab",
    "the stone roses", "stone roses",
    "the shins", "shins ",
    "queens of the stone age", "qotsa",
    "the jam ", "jam ",
    "the b-52's", "the b-52s", "b-52s",
    "cocteau twins",
    "frightened rabbit",
    "mazzy star",
    "animal collective",
    "at the drive-in", "at the drive in",
    "the fall ",
    "pere ubu",
    "the undertones",
    "delta 5",
    "the chameleons",
    "pinback ",
    "millencolin",
    "the la's", "the las ",
    "xtc ",
    "the revivalists",
    "q lazzarus",
    "welcome to the jungle",
    "lenny kravitz",
    "republica ",
    "luke combs",
    "zach bryan",
    "orville peck",
    "zz top",
    "static-x",
    "the troggs",
    "troggs ",
    "brother dege",
    "townes van zandt",
    "stone cold crazy",
    "mac demarco",
    "mudvayne",
    "ministry ",
    "the vaselines",
    "the wedding present",
    "the feelies",
    "the only ones",
    "the raincoats",
    "air miami",
    "electric eels",
    "westernhagen",
    "this mortal coil",
    "a certain ratio",
    "the frights",
    "the bats ",
    "josef k",
    "red krayola",
    "red crayola",
    "ned's atomic dustbin",
    "neds atomic dustbin",
    "dog's eye view",
    "no age ",
    "liliput",
    "shudder to think",
    "swirlies",
    "marine girls",
    "mark hollis",
    "go-betweens",
    "go betweens",
    "jimmie vaughan",
    "the gourds",
    "alien ant farm",
    "a_certain_ratio",
    "a certain radio",
    "buttertones",
    "ghost ",
    "the gist ",
    "jonathan davis",
    "the lively ones",
    "the marketts",
    "linkin par",
    "pacific gas & electric",
    "aliotta haynes",
    "crosby stills",
    "the ex ",
    "the blasters",
    "crosby,",
    "bustin surfboards",
    "magic carpet ride",
    "it's my life",
    "two door cinema",
    "crawling",
    "nick cave",
    "totally wired",
    "inner wave",
    "slow emotion replay",
    "sugar ",
    "if i die young",
    "toten ",
    "lewis del mar",
    "magic city hippies",
    "#1 dads",
    "l'rain",
    "ainslie wills",
    "old sea brigade",
    "heart-",
]

ELECTRONIC_KEYWORDS = [
    # ─ Electronic artists ─
    "arthur russell",
    "moby ",
    "sylvan esso",
    "big wild",
    "stromae",
    "la roux",
    "major lazer",
    "mfinity",
    "anna meredith",
    "deichkind",
    "glass animals",
    "polo & pan", "polo and pan",
    "kraftwerk",
    "new order",
    "joy division",
    "daft punk", "aphex twin", "chemical brothers", "chemical_brothers",
    "prodigy", "the prodigy", "underworld",
    "massive attack", "portishead", "tricky ",
    "deadmau5", "diplo ",
    "flume ", "four tet", "four-tet",
    "caribou", "bonobo", "moderat",
    "boards of canada", "autechre",
    "orbital", "future sound of london",
    "crystal method", "lfo ",
    "squarepusher", "amon tobin",
    "plaid",
    "nightmares on wax",
    "odesza", "madeon",
    "porter robinson", "what so not",
    "kaytranada", "shlohmo",
    "nicolas jaar", "machinedrum",
    "gramatik",
    "pretty lights", "sts9",
    "lcd soundsystem",
    "gesaffelstein",
    "tycho ",
    "celldweller",
    "mr oizo", "mr. oizo",
    "hermitude",
    "pachanga boys",
    "blundetto",
    "joey pecoraro",
    "moreno pezzolato",
    "carbon decay",
    "c2c ",
    "camelphat",
    "the allergies",
    "krono ",
    "mura masa",
    "noizu ",
    "tim berg",
    "whethan",
    "klingande",
    "tungevaag",
    "mousse t",
    "piero pirupa",
    "osunlade",
    "mochakk",
    "roosevelt ",
    "young franco",
    "ian carey",
    "martin solveig",
    "alex gaudino",
    "enur ",
    "calabria ",
    "laurent wolf",
    "alexandra stan",
    "jax jones", "jax_jones",
    "aronchupa",
    "twocolors",
    "wamdue project", "wamdue ",
    "rudenko ",
    "robin_schulz",
    "ida corr",
    "alan walker",
    "a-trak",
    "maribou state",
    "fakear",
    "kerala dust",
    "golden vessel",
    "baynk",
    "black strobe",
    "debruit",
    "light asylum",
    "bellaire",
    "idris dauwd",
    "riton",
    "salt cathedral",
    "tony romera",
    "the supermen lovers",
    "poolside ",
    "sleepy fish",
    "peaches ",
    "yosi horikawa",
    "pilocka krach",
    "etienne jaumet",
    "koreless",
    "fasme",
    "tentendo",
    "stussko",
    "sandhog",
    "coro ",
    "delerium",
    "neil cicierega",
    "passion fruit ",
    "alexander marcus",
    "esg ",
    "rikslyd",
    "tom jarmey",
    "choopsie",
    "tonite only",
    "tobacco ",
    "oka ",
    "naoba",
    "rigopolar",
    "0303am",
    "renan ferrari",
    "arling & cameron", "arling and cameron",
    "giua",
    "deekline",
    "adi ulmansky",
    "ecstasis",
    "elation station",
    "dubdogz",
    "snollebo",
    "numa ",
    "polish ambassador",
    "alban",
    "nghtwrk",
    "hoken",
    "kingdom ",
    "autoload",
    "hermetico",
    "touch and go",
    "snake city",
    "soda ",
    "joost ",
    "bomel",
    "superheld",
    "aerodynamite",
    "hohm",
    "hxrt",
    "mou5zyzz",
    "aiio",
    "møme",
    "insomnia",
    "parallells",
    "sp3ctrum",
    "psyched3lic",
    "peace sine",
    "trainman",
    "tambour battant",
    "vurt",
    "nowifi",
    "intr0beatz",
    "tony shades",
    "orenda",
    "umbilical moonrise",
    "with you friends",
    "art school girlfriend",
    "hundred waters",
    "tkdjs",
    "tabasco project",
    "levyticus",
    "life of dillon",
    "lo wolf",
    "j ember",
    "jaykode",
    "excentric",
    "highbloo",
    "nokturn",
    "antois",
    "countach",
    "shadow age",
    "autumn glow",
    "bliss looper",
    "siren tourist",
    "acheless",
    "cardiac half",
    "claraty",
    "dolce tiva",
    "benji lewis",
    "koni ",
    "rob & chris",
    # ─ Techno artists (remapped from v18 "techno") ─
    "carl cox", "ben klock",
    "marcel dettmann", "adam beyer",
    "blawan", "surgeon",
    "speedy j", "len faki",
    "plastikman", "richie hawtin",
    "sven vath", "sven väth",
    "chris liebing", "sam paganini",
    "joseph capriati", "nina kraviz",
    "dax j", "mndsgn",
    "charlotte de witte",
    "paul kalkbrenner", "kalkbrenner",
    "amelie lens",
    "perc ",
    "pleasurekraft",
    "jan blomqvist",
    "carlita",
    "dan caster",
    # ─ Trance artists (remapped from v18 "trance") ─
    "infected mushroom", "astral projection",
    "gms ", "perfect stranger", "sun project", "loud ",
    "vini vici", "captain hook", "ace ventura",
    "skazi", "talamasca", "x-dream",
    "astrix", "juno reactor", "hallucinogen",
    "simon posford", "shpongle",
    "avalon ", "oforia", "ubar tmar",
    "1200 mics", "riktam",
    "sol tribe", "alien project",
    "psysex",
    "1200 micrograms", "1200mcg",
    "outsiders & dickster",
    "tristan & biggs",
    "dubtazer",
    "darwish",
    "parasense", "vibrasphere",
    "cosmosis", "transwave",
    "total eclipse", "psyphenomenon",
    "armin van buuren", "van buuren",
    "paul van dyk",
    "sasha ", "john digweed",
    "markus schulz", "paul oakenfold",
    "ferry corsten", "tiesto", "tiësto",
    "above & beyond", "above and beyond",
    "giuseppe ottaviani", "solarstone",
    "factor b", "bryan kearney",
    "aly & fila", "aly and fila",
    "gareth emery", "andrew rayel",
    "dash berlin", "cosmic gate",
    "judge jules", "mike shiver",
    "simon & biggs", "chicane",
    "rank 1", "rank1", "push ", "svenson",
    "binary finary",
    "omnia ",
    "ilan bluestone",
    "denis kenzo",
    "kryder",
    "arty ",
    "genix",
    "super8 & tab", "super8 and tab",
    "rodg ",
    "estiva",
    "david gravell",
    "simon lee & alvin", "simon lee and alvin",
    "alexander popov",
    "drym",
    "luke bond",
    "orjan nilsen", "ørjan nilsen",
    "ana criado",
    "andrew bayer",
    "ashley wallbridge",
    "christina novelli",
    "alexandra badoi",
    "frainbreeze",
    "guru josh",
    "tom wax",
    "willem de roo",
    # ─ World ambient/downtempo artists (remapped from v18 "world") ─
    "bird tribe",
    "omar souleyman",
    "akriza",
    "banyan",
    "prem joshua",
    "thornato",
    "tahum", "tahüm",
    "equanimous",
    "eye of the forest", "east forest",
    "this is flow",
    "fatoumata diawara",
    "habib koite",
    "amadou & mariam", "amadou and mariam",
    "bombino",
    "tinariwen",
    "bassekou kouyate",
    "toumani diabate",
    "ballaké sissoko", "ballake sissoko",
    "rokia traore", "rokia traoré",
    "ismael lo",
    "aby ngana diop",
    "nusrat fateh ali khan",
    "abida parveen",
    "ali hassan kuban",
    "nour eddine",
    "mahmoud guinia",
    "hamid el kasri",
    "deben bhattacharya",
    "l. shankar",
    "anoushka shankar",
    "ravi shankar",
    "ali akbar khan",
    "sultan khan",
    "zakir hussain",
    "bulgarian voices",
    "le mystere des voix",
    "klezmatics",
    "frank london",
    "david krakauer",
    "golem ",
    "los calchakis",
    "los kjarkas",
    "khaled ",
    "yasmine hamdan",
    "oi va voi",
    "mory kanté", "mory kante",
    "mercan dede",
    "fanfare ciocarlia",
    "zventa sventana",
    "islandman",
    "shintaro sakamoto",
    "rostam ",
    "sharmoofers",
    "joao selva",
    "playing for change",
    "laya project",
    "quantic",
    "planet drum",
    "drumspyder",
    "james asher",
    "gcm",
    "khululuma",
    "eastern journey",
    "zamfir",
    "yemanjo",
    "guru singh",
    "omkara",
    "jain ",
    "xavier rudd",
    "danit ",
    "xenia ",
    "jpattersson",
    "shakti bliss",
    "dj drez",
    "climbing poetree",
    "vision dojo",
    "human experience",
    "voilaaa",
    "sara tavares",
    "hotei ",
    "meiko kaji",
    # ─ Genre terms ─
    "ambient ",
    "edm ", "electro ",
    "synth ", "synthwave",
    "breaks ", "breakbeat",
    "glitch hop", "glitch",
    "idm ", "experimental",
    "downtempo", "trip hop", "trip-hop", "triphop",
    "chillout", "chill out", "chill-out", "balearic",
    "vaporwave", "synthpop", "synth-pop", "synth pop",
    "darkwave", "dark wave", "coldwave", "cold wave",
    "industrial ", "ebm ", "aggrotech",
    "future garage", "future house",
    "8bit", "chiptune", "bitpop",
    "folktronica", "indietronica",
    "noise ", "japanoise", "power electronics",
    "drone ", "dark ambient",
    "lo-fi ", "lofi ",
    # ─ Techno genre terms (remapped from v18 "techno") ─
    "techno ",
    "acid techno", "detroit techno", "minimal techno", "schranz",
    "melodic techno",
    "hardstyle", "hardcore", "gabber",
    "uk hardcore", "happy hardcore", "makina ",
    "jumpstyle", "hardstep",
    # ─ Trance genre terms (remapped from v18 "trance") ─
    "psytrance", "psy trance", "psy-trance",
    "goa trance", "goa ",
    "progressive psy", "full on", "fullon",
    "trance ",
    "acid trance", "uplifting trance", "vocal trance", "hard trance",
    "dark psy", "dark psytrance", "suomisaundi",
    # ─ World ambient/spiritual genre terms (remapped from v18 "world") ─
    "world music", "global",
    "qawwali", "sufi",
    "didgeridoo", "native american",
    "deep forest", "enigma ",
    "world beat",
    "afro-house",
    "mbalax", "juju ", "fuji music",
    "gnawa", "rai ", "raï ",
    "bhangra", "bollywood", "filmi ",
    "dangdut", "gamelan",
    "celtic ", "klezmer", "balkan",
    "polka ", "zydeco",
    "throat singing", "overtone singing",
    "ecstatic dance", "kirtan", "mantra",
    "shamanic", "medicine music", "sound healing",
    "tribal ", "ethno ", "ethnic ",
    "arabic", "arab ", "oud ", "tabla ",
    "turkish", "greek laika",
]

COUNTRY_KEYWORDS = [
    # ─ Country artists ─
    "johnny cash",
    "dolly parton",
    "kenny rogers",
    "emmylou harris",
    "glen campbell",
    "willie nelson",
    "waylon jennings",
    "merle haggard",
    "hank williams",
    "patsy cline",
    "loretta lynn",
    "tammy wynette",
    "george strait",
    "garth brooks",
    "alan jackson",
    "tim mcgraw",
    "faith hill",
    "shania twain",
    "kenny loggins",
    "john mellencamp", "john cougar",
    "luke combs",
    "zach bryan",
    "morgan wallen",
    "kacey musgraves",
    "orville peck",
    "rascal flatts",
    "the band perry",
    "the mavericks",
    "john prine",
    "townes van zandt",
    "brother dege",
    # ─ Genre terms ─
    "country", "nashville", "country pop", "country rock",
    "bluegrass", "honky tonk", "country western",
    "alt-country", "americana", "outlaw country",
    "country folk", "neo-traditional country",
    "new country",
]

# ─────────────────────────────────────────────────────────────────────────────
# Master mapping — used by the classifier engine
# ─────────────────────────────────────────────────────────────────────────────
# NOTE: Locale genres (israeli, arabic, etc.) are NOT here — they use character detection only.
# NOTE: "classics" is NOT here — detected by year range, not keywords.

GENRE_KEYWORDS = {
    "tools": TOOLS_KEYWORDS,
    "house": HOUSE_KEYWORDS,
    "amapiano": AMAPIANO_KEYWORDS,
    "afrobeats": AFROBEATS_KEYWORDS,
    "reggae_dancehall": REGGAE_DANCEHALL_KEYWORDS,
    "hiphop": HIPHOP_KEYWORDS,
    "latin": LATIN_KEYWORDS,
    "bass_dnb_garage": BASS_DNB_GARAGE_KEYWORDS,
    "pop": POP_KEYWORDS,
    "funk_disco_soul": FUNK_DISCO_SOUL_KEYWORDS,
    "rock": ROCK_KEYWORDS,
    "electronic": ELECTRONIC_KEYWORDS,
    "country": COUNTRY_KEYWORDS,
}
